<?php

$destinations = [
    [
        'name' => 'Srinagar',
        'state' => 'Jammu & Kashmir',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/srinagar.jpg',
        'attractions' => ['Dal Lake', 'Mughal Gardens', 'Shankaracharya Temple', 'Hazratbal Shrine', 'Nishat Bagh', 'Chashme Shahi', 'Pari Mahal'],
        'attractions_images' => [
            'images/destination/srinnagar/dal_lake.jpg',
            'images/destination/srinnagar/mughal_gardens.jpg',
            'images/destination/srinnagar/shankaracharya_temple.jpg',
            'images/destination/srinnagar/hazratbal_shrine.jpg',
            'images/destination/srinnagar/nishat_bagh.jpg',
            'images/destination/srinnagar/chashme_shahi.jpg',
            'images/destination/srinnagar/pari_mahal.jpg'
        ],
        'festivals' => ['Tulip Festival', 'Shikara Festival', 'Srinagar Festival', 'Navroz', 'Urs of Sheikh Nooruddin', 'Baisakhi', 'Saffron Festival'],
        'cuisines' => ['Rogan Josh', 'Dum Aloo', 'Kahwa', 'Yakhni', 'Gushtaba', 'Nadir Monji', 'Haaq'],
        'famous_spots' => ['Shikara Ride at Dal Lake', 'Floating Market', 'Café de Linz', 'Shalimar Bagh', 'Khanqah-e-Moula', 'Char Chinar', 'Harwan Garden'],
        'nearby' => ['Gulmarg', 'Sonamarg', 'Pahalgam', 'Yusmarg', 'Dachigam National Park', 'Aru Valley', 'Betaab Valley'],
        'description' => 'Srinagar, the heart of Kashmir Valley, is a city where nature and culture intertwine seamlessly. Set against the backdrop of the Zabarwan Mountains, it is renowned for its shimmering lakes, historic gardens, and vibrant houseboat culture. Visitors are captivated by the serene Dal Lake, where shikara rides offer glimpses of floating markets and lotus blooms. The city’s Mughal gardens, laid out in Persian style, showcase meticulous landscaping and cascading fountains, while its spiritual sites like Shankaracharya Temple offer panoramic views and peace. Srinagar’s bustling markets, rich handicrafts (Pashmina shawls, carpets), and warm hospitality make it a must-visit for those seeking a blend of relaxation and exploration.',
        'state_context' => 'Jammu & Kashmir, nestled in the northernmost part of India, is a region of unparalleled natural beauty and cultural richness, often called "Paradise on Earth." Bordered by the Himalayas, it features serene lakes, lush valleys, and snow-capped peaks, with Srinagar as its summer capital. The state’s history is a tapestry of Hindu, Buddhist, and Islamic influences, reflected in its architecture, cuisine, and festivals. Despite its complex socio-political landscape, Jammu & Kashmir remains a haven for travelers seeking tranquility and adventure, with Srinagar’s Dal Lake and Mughal gardens epitomizing its charm.
',
        'attractions_descriptions' => [
            'Dal Lake is the jewel of Srinagar, famous for its shikara rides and floating gardens.',
            'Mughal Gardens showcase exquisite Persian-style landscaping with vibrant flowerbeds.',
            'Shankaracharya Temple, perched on a hill, offers spiritual solace and panoramic views.',
            'Hazratbal Shrine, a revered Muslim site, is known for its serene lakeside location.',
            'Nishat Bagh, a Mughal garden, is a terraced marvel with stunning lake views.',
            'Chashme Shahi, another Mughal garden, is famous for its natural spring.',
            'Pari Mahal, a historic monument, blends architecture with breathtaking vistas.'
        ]
    ],
    [
        'name' => 'Leh-Ladakh',
        'state' => 'Jammu & Kashmir',
        'budget' => 'Luxury',
        'type' => 'Adventure',
        'duration' => 'Week-long',
        'image' => 'images/destination/leh_ladakh.jpg',
        'attractions' => ['Pangong Lake', 'Magnetic Hill', 'Thiksey Monastery', 'Nubra Valley', 'Hemis Monastery', 'Shanti Stupa', 'Zanskar Valley'],
        'attractions_images' => [
            'images/destination/leh-ladakh/pongong_lake.jpg',
            'images/destination/leh-ladakh/magnetic_hill.jpg',
            'images/destination/leh-ladakh/thicksey_monastry.jpg',
            'images/destination/leh-ladakh/nubra_valley.jpg',
            'images/destination/leh-ladakh/hemis_monastery.jpg',
            'images/destination/leh-ladakh/shanti_stupa.jpg',
            'images/destination/leh-ladakh/zanskar_valley.jpg'
        ],
        'festivals' => ['Hemis Festival', 'Losar Festival', 'Ladakh Festival', 'Sindhu Darshan', 'Thiksey Gustor', 'Spituk Gustor', 'Dosmoche Festival'],
        'cuisines' => ['Thukpa', 'Momos', 'Skyu', 'Butter Tea', 'Chhutagi', 'Paba', 'Tingmo'],
        'famous_spots' => ['Leh Market', 'Leh Palace', 'German Bakery', 'Hall of Fame', 'Sangam (Confluence)', 'Diskit Monastery', 'Tso Kar Lake'],
        'nearby' => ['Nubra Valley', 'Tso Moriri Lake', 'Kargil', 'Alchi', 'Lamayuru', 'Stok Village', 'Dras'],
        'description' => 'Leh-Ladakh is an adventurer’s paradise, where dramatic landscapes meet ancient spirituality. At over 3,500 meters, Leh town buzzes with markets, monasteries, and cafes, serving as the gateway to Ladakh’s wonders. From the azure Pangong Lake to the gravity-defying Magnetic Hill, every site feels otherworldly. The region’s monasteries, like Thiksey and Hemis, offer glimpses into Tibetan Buddhism, while rugged terrains like Nubra and Zanskar valleys beckon trekkers and bikers. Ladakh’s stark beauty, clear skies (perfect for stargazing), and cultural richness make it a bucket-list destination for thrill-seekers and soul-searchers alike.',
        'state_context' => 'Jammu & Kashmir’s diverse geography extends to the rugged, high-altitude desert of Ladakh, a land of stark beauty and spiritual depth. Known as “Little Tibet,” Ladakh’s Buddhist monasteries, barren mountains, and turquoise lakes create a surreal landscape. Its sparse population and extreme climate foster a unique culture of resilience and hospitality, with Leh as the vibrant hub for travelers exploring this remote region.',

        'attractions_descriptions' => [
            'Pangong Lake is a mesmerizing turquoise lake, famous for its ever-changing hues.',
            'Magnetic Hill defies gravity, where vehicles seem to roll uphill on their own.',
            'Thiksey Monastery is a stunning Buddhist complex resembling the Potala Palace.',
            'Nubra Valley offers surreal landscapes with sand dunes and double-humped camels.',
            'Hemis Monastery is a cultural hub, known for its vibrant annual festival.',
            'Shanti Stupa provides peace and sweeping views of Leh’s rugged terrain.',
            'Zanskar Valley is a remote paradise for trekkers and adventure enthusiasts.'
        ]
    ],
    [
        'name' => 'Shimla',
        'state' => 'Himachal Pradesh',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/shimla.jpg',
        'attractions' => ['The Ridge', 'Mall Road', 'Jakhu Temple', 'Viceregal Lodge', 'Christ Church', 'Annandale', 'Kali Bari Temple'],
        'attractions_images' => [
            'images/destination/shimla/the_ridge.jpg',
            'images/destination/shimla/mall_road.jpg',
            'images/destination/shimla/jakhu_temple.jpg',
            'images/destination/shimla/viceregal_lodge.jpg',
            'images/destination/shimla/christ_church.jpg',
            'images/destination/shimla/annandale.jpg',
            'images/destination/shimla/kali_bari_temple.jpg'
        ],
        'festivals' => ['Summer Festival', 'Ice Skating Carnival', 'Shimla Winter Carnival', 'Baisakhi Mela', 'Lavi Fair', 'Holi Festival', 'Christmas Celebrations'],
        'cuisines' => ['Chana Madra', 'Siddu', 'Babru', 'Himachali Trout', 'Dham', 'Patande', 'Sepu Vadi'],
        'famous_spots' => ['Scandal Point', 'Indian Coffee House', 'Christ Church', 'Lakkar Bazaar', 'Green Valley', 'Toy Train Ride', 'State Museum'],
        'nearby' => ['Kufri', 'Chail', 'Narkanda', 'Mashobra', 'Fagu', 'Tattapani', 'Naldehra'],
        'description' => 'Shimla, the charming hill station of Himachal Pradesh, is known for its colonial architecture, scenic beauty, and vibrant culture. It’s a perfect getaway for a relaxing weekend.',
        'state_context' => 'Himachal Pradesh is a northern Indian state celebrated for its lush hills, adventure sports, and spiritual retreats. Shimla, its capital, retains a colonial charm alongside natural splendor.',
        'attractions_descriptions' => [
            'The Ridge is a vibrant open space with stunning mountain views and cultural events.',
            'Mall Road is Shimla’s bustling heart, lined with shops, cafes, and colonial buildings.',
            'Jakhu Temple is a sacred site dedicated to Lord Hanuman, perched on a hilltop.',
            'Viceregal Lodge is a historic colonial mansion with beautiful gardens.',
            'Christ Church, a neo-Gothic landmark, is one of India’s oldest churches.',
            'Annandale is a scenic ground known for golf, picnics, and polo matches.',
            'Kali Bari Temple is a serene shrine dedicated to Goddess Kali, attracting devotees.'
        ]
    ],
    [
        'name' => 'Manali',
        'state' => 'Himachal Pradesh',
        'budget' => 'Mid-range',
        'type' => 'Adventure',
        'duration' => '5-day',
        'image' => 'images/destination/manali.jpg',
        'attractions' => ['Solang Valley', 'Hadimba Temple', 'Rohtang Pass', 'Vashisht Hot Springs', 'Manu Temple', 'Jogini Falls', 'Beas Kund'],
        'attractions_images' => [
            'images/destination/manali/solang_valley.jpg',
            'images/destination/manali/hadimba_temple.jpg',
            'images/destination/manali/rohtang_pass.jpg',
            'images/destination/manali/vashisht_hot_spring.jpg',
            'images/destination/manali/manu_temple.jpg',
            'images/destination/manali/jogini_falls.jpg',
            'images/destination/manali/beas_kund.jpg'
        ],
        'festivals' => ['Dussehra Festival', 'Winter Carnival', 'Kullu Dussehra', 'Hadimba Devi Fair', 'Spring Festival', 'Holi Festival', 'Losar Festival'],
        'cuisines' => ['Siddu', 'Trout Fish', 'Babru', 'Mittha', 'Dham', 'Chana Madra', 'Kullu Puti'],
        'famous_spots' => ['Old Manali Cafes', 'Manali Club House', 'Manu Temple', 'Tibetan Monastery', 'Naggar Castle', 'Van Vihar', 'Mall Road'],
        'nearby' => ['Naggar', 'Kasol', 'Kullu', 'Manikaran', 'Rohtang La', 'Parvati Valley', 'Sissu'],
        'description' => 'Manali is a vibrant hill station in Himachal Pradesh, offering adventure, spirituality, and stunning Himalayan views. It’s a hotspot for trekkers, skiers, and nature lovers.',
        'state_context' => 'Himachal Pradesh, nestled in the Himalayas, is renowned for its adventure tourism and serene landscapes. Manali is a gateway to thrilling experiences and cultural exploration.',
        'attractions_descriptions' => [
            'Solang Valley is a paradise for adventure sports like paragliding and zorbing.',
            'Hadimba Temple is an ancient wooden shrine surrounded by cedar forests.',
            'Rohtang Pass offers breathtaking views and snow activities in season.',
            'Vashisht Hot Springs are natural thermal springs with healing properties.',
            'Manu Temple is a sacred site dedicated to the sage Manu, steeped in mythology.',
            'Jogini Falls is a scenic waterfall perfect for treks and picnics.',
            'Beas Kund is a pristine high-altitude lake, a trekker’s delight.'
        ]
    ],
    [
        'name' => 'Nainital',
        'state' => 'Uttarakhand',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/nainital.jpg',
        'attractions' => ['Naini Lake', 'Snow View Point', 'Naina Devi Temple', 'Tiffin Top', 'Eco Cave Gardens', 'High Altitude Zoo', 'Naina Peak'],
        'attractions_images' => [
            'images/destination/nainital/naini_lake.jpg',
            'images/destination/nainital/snow_view_point.jpg',
            'images/destination/nainital/naina_devi_temple.jpg',
            'images/destination/nainital/tiffin_top.jpg',
            'images/destination/nainital/eco_cave_gardens.jpg',
            'images/destination/nainital/high_altitude_zoo.jpg',
            'images/destination/nainital/naina_peak.jpg'
        ],
        'festivals' => ['Nanda Devi Fair', 'Autumn Festival', 'Phool Dei', 'Holi Festival', 'Diwali Mela', 'Sharadotsav', 'Uttarayani Fair'],
        'cuisines' => ['Aloo Ke Gutke', 'Bhatt Ki Churkani', 'Bal Mithai', 'Ras Bhaat', 'Kafuli', 'Singori', 'Phaanu'],
        'famous_spots' => ['Café Lakeside', 'Tiffin Top', 'Nainital Zoo', 'Mall Road', 'Governor’s House', 'St. John’s Church', 'Hanuman Garhi'],
        'nearby' => ['Bhimtal', 'Naukuchiatal', 'Sattal', 'Ranikhet', 'Almora', 'Mukteshwar', 'Kausani'],
        'description' => 'Nainital, a picturesque hill station in Uttarakhand, is centered around the serene Naini Lake, offering tranquility and scenic beauty. It’s ideal for a relaxing weekend escape.',
        'state_context' => 'Uttarakhand, known as the “Land of Gods,” is famous for its Himalayan landscapes and spiritual centers. Nainital is a jewel in its crown, blending nature and culture.',
        'attractions_descriptions' => [
            'Naini Lake is a serene emerald lake, perfect for boating and evening strolls.',
            'Snow View Point offers stunning Himalayan vistas via a scenic cable car ride.',
            'Naina Devi Temple is a sacred shrine by the lake, revered by locals.',
            'Tiffin Top provides panoramic views of Nainital and the surrounding hills.',
            'Eco Cave Gardens are a network of caves and hanging gardens for families.',
            'High Altitude Zoo houses rare Himalayan wildlife like snow leopards.',
            'Naina Peak is a trekking spot with breathtaking views of the town below.'
        ]
    ],
    [
        'name' => 'Gangtok',
        'state' => 'Sikkim',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/gangtok.jpg',
        'attractions' => ['Tsomgo Lake', 'Rumtek Monastery', 'Nathula Pass', 'Enchey Monastery', 'Ban Jhakri Falls', 'Hanuman Tok', 'Do-Drul Chorten'],
        'attractions_images' => [
            'images/destination/gangtok/tmsao_lake.jpg',
            'images/destination/gangtok/rumtek_monastery.jpg',
            'images/destination/gangtok/nathula_pass.jpg',
            'images/destination/gangtok/enchey_monastery.jpg',
            'images/destination/gangtok/ban_jhakri-falls.jpg',
            'images/destination/gangtok/hanuman_tok.png',
            'images/destination/gangtok/do_drul_chorten.jpg'
        ],
        'festivals' => ['Losar Festival', 'Saga Dawa Festival', 'Pang Lhabsol', 'Dasain Festival', 'Tihar Festival', 'Bumchu Festival', 'Drukpa Tsheshi'],
        'cuisines' => ['Phagshapa', 'Thukpa', 'Momos', 'Sel Roti', 'Gundruk', 'Sinki Soup', 'Chhurpi'],
        'famous_spots' => ['MG Marg', 'Baker’s Café', 'Flower Exhibition Centre', 'Tashi View Point', 'Gangtok Ropeway', 'Sikkim Himalayan Zoo', 'Café Live & Loud'],
        'nearby' => ['Namchi', 'Pelling', 'Ravangla', 'Yuksom', 'Lachung', 'Lachen', 'Zuluk'],
        'description' => 'Gangtok, the capital of Sikkim, is a vibrant hill city known for its monasteries, scenic lakes, and warm hospitality. It’s a gateway to Sikkim’s natural and cultural treasures.',
        'state_context' => 'Sikkim, India’s smallest state, is a biodiversity hotspot with rich Buddhist heritage and Himalayan vistas. Gangtok serves as its cultural and administrative hub.',
        'attractions_descriptions' => [
            'Tsomgo Lake is a glacial lake revered for its crystal-clear waters and serenity.',
            'Rumtek Monastery is a major Buddhist center with intricate architecture.',
            'Nathula Pass, a high-altitude border pass, offers stunning views and history.',
            'Enchey Monastery is a 200-year-old shrine with peaceful ambiance.',
            'Ban Jhakri Falls is a scenic waterfall with a cultural theme park.',
            'Hanuman Tok is a hilltop temple with panoramic views of Kanchenjunga.',
            'Do-Drul Chorten is a significant stupa surrounded by prayer wheels.'
        ]
    ],
    [
        'name' => 'Shillong',
        'state' => 'Meghalaya',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/shillong.jpg',
        'attractions' => ['Elephant Falls', 'Umiam Lake', 'Shillong Peak', 'Ward’s Lake', 'Lady Hydari Park', 'Laitlum Canyons', 'Cathedral of Mary'],
        'attractions_images' => [
            'images/destination/shillong/elephant_falls.jpg',
            'images/destination/shillong/umimam_lake.jpg',
            'images/destination/shillong/shillong_peak.jpg',
            'images/destination/shillong/wards_lake.jpg',
            'images/destination/shillong/lady_hydari_park.jpg',
            'images/destination/shillong/laitlum_canyons.jpg',
            'images/destination/shillong/cathedral_of_mary.jpg'
        ],
        'festivals' => ['Shad Suk Mynsiem', 'Wangala Festival', 'Nongkrem Dance Festival', 'Behdienkhlam Festival', 'Strawberry Festival', 'Christmas Festival', 'Meghalaya Day'],
        'cuisines' => ['Jadoh', 'Dohneiiong', 'Tungrymbai', 'Pukhlein', 'Nakham Bitchi', 'Pumaloi', 'Dohjem'],
        'famous_spots' => ['Café Shillong', 'Don Bosco Museum', 'Police Bazar', 'Mawjymbuin Cave', 'Air Force Museum', 'All Saints-absolute', 'Butterfly Museum'],
        'nearby' => ['Cherrapunji', 'Mawlynnong', 'Dawki', 'Mawsynram', 'Nongpoh', 'Jowai', 'Nartiang'],
        'description' => 'Shillong, the "Scotland of the East," is Meghalaya’s capital, known for its rolling hills, waterfalls, and vibrant music scene. It’s a perfect blend of nature and urban charm.',
        'state_context' => 'Meghalaya, meaning "abode of clouds," is a northeastern state with lush landscapes and indigenous Khasi culture. Shillong is its cultural and musical epicenter.',
        'attractions_descriptions' => [
            'Elephant Falls is a three-tiered waterfall surrounded by lush greenery.',
            'Umiam Lake is a serene reservoir ideal for boating and picnics.',
            'Shillong Peak offers panoramic views of the city and hills.',
            'Ward’s Lake is a picturesque man-made lake with gardens and boating.',
            'Lady Hydari Park is a tranquil park with a mini zoo and flowerbeds.',
            'Laitlum Canyons provide dramatic vistas of Meghalaya’s rugged terrain.',
            'Cathedral of Mary is a stunning Gothic-style church in the heart of Shillong.'
        ]
    ],
    [
        'name' => 'Kaziranga',
        'state' => 'Assam',
        'budget' => 'Mid-range',
        'type' => 'Adventure',
        'duration' => '5-day',
        'image' => 'images/destination/kaziranga.jpg',
        'attractions' => ['Elephant Safaris', 'Jeep Safari', 'Tea Gardens', 'Kaziranga Orchid Park', 'Panbari Reserve', 'Kakochang Falls', 'Deopahar Ruins'],
        'attractions_images' => [
            'images/destination/kaziranga/elephant_safaris.png',
            'images/destination/kaziranga/jeep_safari.jpg',
            'images/destination/kaziranga/tea_garden.jpg',
            'images/destination/kaziranga/kaziranga_orchid_park.jpg',
            'images/destination/kaziranga/panbari_reserve.jpg',
            'images/destination/kaziranga/kakochang_falls.jpg',
            'images/destination/kaziranga/deopahar_ruins.jpg'
        ],
        'festivals' => ['Bihu Festival', 'Kaziranga Elephant Festival', 'Tea Festival', 'Ambubachi Mela', 'Dehing Patkai Festival', 'Ras Mahotsav', 'Majuli Festival'],
        'cuisines' => ['Masor Tenga', 'Khar', 'Duck Meat Curry', 'Pitika', 'Pork Anishi', 'Aloo Pitika', 'Ou Tenga'],
        'famous_spots' => ['Kaziranga Orchid Park', 'Local Tea Gardens', 'Ethnic Village Restaurant', 'Hathikuli Tea Estate', 'Brahmaputra River Bank', 'Kohora Village', 'Rangmon Bird Watching'],
        'nearby' => ['Majuli', 'Tezpur', 'Jorhat', 'Sivsagar', 'Dibrugarh', 'Golaghat', 'Hoollongapar Gibbon Sanctuary'],
        'description' => 'Kaziranga, a UNESCO World Heritage Site in Assam, is famed for its one-horned rhinoceros and diverse wildlife. It’s a paradise for nature lovers and adventure seekers.',
        'state_context' => 'Assam, in northeastern India, is known for its tea plantations, Brahmaputra River, and rich biodiversity. Kaziranga is a crown jewel of its wildlife conservation efforts.',
        'attractions_descriptions' => [
            'Elephant Safaris offer an intimate way to explore Kaziranga’s wildlife.',
            'Jeep Safari provides thrilling rides through the park’s diverse ecosystems.',
            'Tea Gardens showcase Assam’s world-famous tea production heritage.',
            'Kaziranga Orchid Park displays vibrant orchids and local culture.',
            'Panbari Reserve is a quieter area for spotting rhinos and birds.',
            'Kakochang Falls is a scenic waterfall ideal for nature outings.',
            'Deopahar Ruins reveal ancient archaeological remnants amidst greenery.'
        ]
    ],
    [
        'name' => 'Jaipur',
        'state' => 'Rajasthan',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/jaipur/hawa_mahal.jpg',
        'attractions' => ['Hawa Mahal', 'Amber Fort', 'City Palace', 'Jantar Mantar', 'Nahargarh Fort', 'Jaigarh Fort', 'Albert Hall Museum'],
        'attractions_images' => [
            'images/destination/jaipur.jpg',
            'images/destination/jaipur/amber_fort.jpg',
            'images/destination/jaipur/city_palace.jpeg',
            'images/destination/jaipur/jantar_mantar.jpg',
            'images/destination/jaipur/nahargarh_fort.jpg',
            'images/destination/jaipur/jaigarh_fort.jpg',
            'images/destination/jaipur/albert_hall_museum.jpg'
        ],
        'festivals' => ['Jaipur Literature Festival', 'Teej Festival', 'Diwali Festival', 'Gangaur Festival', 'Kite Festival', 'Elephant Festival', 'Pushkar Fair'],
        'cuisines' => ['Dal Baati Churma', 'Laal Maas', 'Ghewar', 'Ker Sangri', 'Pyaaz Kachori', 'Mawa Kachori', 'Rajasthani Thali'],
        'famous_spots' => ['Patrika Gate', 'Masala Chowk', 'Albert Hall Museum', 'Chokhi Dhani', 'Jal Mahal', 'Hathi Gaon', 'Bapu Bazaar'],
        'nearby' => ['Ajmer', 'Pushkar', 'Alwar', 'Ranthambore', 'Neemrana', 'Bharatpur', 'Tonk'],
        'description' => 'Jaipur, the Pink City, is Rajasthan’s vibrant capital, known for its majestic forts, palaces, and rich heritage. It’s a cultural hub with a colorful history.',
        'state_context' => 'Rajasthan, India’s largest state, is synonymous with royal history, desert landscapes, and vibrant festivals. Jaipur embodies its regal and artistic legacy.',
        'attractions_descriptions' => [
            'Hawa Mahal, the Palace of Winds, is famous for its intricate latticework.',
            'Amber Fort is a grand hilltop fortress with stunning architecture.',
            'City Palace blends Mughal and Rajput styles, housing a royal museum.',
            'Jantar Mantar is a UNESCO-listed astronomical observatory.',
            'Nahargarh Fort offers sweeping views of Jaipur’s skyline.',
            'Jaigarh Fort is known for its massive cannon and robust defenses.',
            'Albert Hall Museum showcases Rajasthan’s art and history.'
        ]
    ],
    [
        'name' => 'Varanasi',
        'state' => 'Uttar Pradesh',
        'budget' => 'Budget',
        'type' => 'Spiritual',
        'duration' => '5-day',
        'image' => 'images/destination/varanasi.jpg',
        'attractions' => ['Kashi Vishwanath Temple', 'Dashashwamedh Ghat', 'Sarnath', 'Assi Ghat', 'Manikarnika Ghat', 'Ramnagar Fort', 'Bharat Mata Temple'],
        'attractions_images' => [
            'images/destination/varanasi/kashi_vishwanath_temple.webp',
            'images/destination/varanasi/dashashwamedh_ghat.jpg',
            'images/destination/varanasi/sarnath.jpg',
            'images/destination/varanasi/assi_ghat.jpg',
            'images/destination/varanasi/manikarnika_ghat.jpg',
            'images/destination/varanasi/ramnagar_fort.jpg',
            'images/destination/varanasi/bharat_mata_temple.jpg'
        ],
        'festivals' => ['Dev Deepawali', 'Ganga Mahotsav', 'Maha Shivaratri', 'Holi Festival', 'Buddha Purnima', 'Diwali Festival', 'Chhath Puja'],
        'cuisines' => ['Kachori Sabzi', 'Tamatar Chaat', 'Baati Chokha', 'Malaiyo', 'Litti Chokha', 'Puri Sabzi', 'Banarasi Paan'],
        'famous_spots' => ['Blue Lassi Shop', 'Assi Ghat', 'Banaras Hindu University', 'Gyanvapi Mosque', 'Sankat Mochan Temple', 'Kashi Kalash Foundation', 'Man Mandir Ghat'],
        'nearby' => ['Sarnath', 'Allahabad', 'Ayodhya', 'Mirzapur', 'Chunar', 'Jaunpur', 'Vindhyachal'],
        'description' => 'Varanasi, one of the world’s oldest cities, is India’s spiritual capital, known for its sacred ghats, temples, and vibrant Ganges River rituals.',
        'state_context' => 'Uttar Pradesh, India’s most populous state, is a cultural and historical hub. Varanasi, its spiritual heart, draws millions for its religious significance.',
        'attractions_descriptions' => [
            'Kashi Vishwanath Temple is a revered shrine dedicated to Lord Shiva.',
            'Dashashwamedh Ghat hosts the iconic Ganga Aarti every evening.',
            'Sarnath is a Buddhist pilgrimage site where Buddha gave his first sermon.',
            'Assi Ghat is a lively spot for sunrise views and cultural events.',
            'Manikarnika Ghat is a sacred cremation site steeped in tradition.',
            'Ramnagar Fort houses a museum and offers riverfront views.',
            'Bharat Mata Temple is dedicated to Mother India with a unique marble map.'
        ]
    ],
    [
        'name' => 'Kasol',
        'state' => 'Himachal Pradesh',
        'budget' => 'Budget',
        'type' => 'Offbeat',
        'duration' => 'Weekend',
        'image' => 'images/destination/kasol.jpg',
        'attractions' => ['Parvati Valley', 'Kheerganga Trek', 'Manikaran Sahib', 'Tosh Village', 'Chalal Trek', 'Rasol Village', 'Malana Village'],
        'attractions_images' => [
            'images/destination/kasol/parvati_valley.jpg',
            'images/destination/kasol/kheerganga_trek.jpg',
            'images/destination/kasol/manikaran_sahib.avif',
            'images/destination/kasol/tosh_village.jpg',
            'images/destination/kasol/chalal_trek.jpg',
            'images/destination/kasol/rasol_village.jpg',
            'images/destination/kasol/malana_village.jpg'
        ],
        'festivals' => ['Indrasan Festival', 'Himalayan Music Festival', 'Parvati Peeth Festival', 'Holi Festival', 'Kullu Dussehra', 'Shivratri Festival', 'Baisakhi'],
        'cuisines' => ['Israeli Salad', 'Shakshuka', 'Tandoori Trout', 'Falafel', 'Hummus Platter', 'Nutella Pancakes', 'Himachali Dham'],
        'famous_spots' => ['Moon Dance Café', 'Jim Morrison Café', 'Tosh Village', 'Evergreen Café', 'Bhoj Café', 'Parvati River Bank', 'The Psychedelic'],
        'nearby' => ['Malana', 'Manikaran', 'Tosh', 'Pulga', 'Barshaini', 'Nakthan', 'Kutla'],
        'description' => 'Kasol, a quaint village in Himachal Pradesh’s Parvati Valley, is a backpacker’s paradise known for its scenic treks, vibrant cafes, and laid-back vibe.',
        'state_context' => 'Himachal Pradesh is a haven for adventure and offbeat travel. Kasol, in its Parvati Valley, attracts global travelers for its unique blend of nature and culture.',
        'attractions_descriptions' => [
            'Parvati Valley is a scenic haven with lush trails and serene rivers.',
            'Kheerganga Trek leads to natural hot springs amidst Himalayan views.',
            'Manikaran Sahib is a sacred Sikh and Hindu pilgrimage site with hot springs.',
            'Tosh Village is a tranquil hamlet known for its hippie vibe and cafes.',
            'Chalal Trek offers a short, scenic walk to a peaceful village.',
            'Rasol Village is a hidden gem with rustic charm and trekking trails.',
            'Malana Village is famous for its unique culture and ancient traditions.'
        ]
    ],
    [
        'name' => 'Rishikesh',
        'state' => 'Uttarakhand',
        'budget' => 'Budget',
        'type' => 'Spiritual',
        'duration' => '5-day',
        'image' => 'images/destination/rishikesh.jpg',
        'attractions' => ['Lakshman Jhula', 'Neelkanth Mahadev Temple', 'River Rafting', 'Triveni Ghat', 'The Beatles Ashram', 'Ram Jhula', 'Parmarth Niketan'],
        'attractions_images' => [
            'images/destination/rishikesh/lakshman_jhula.jpg',
            'images/destination/rishikesh/neelkanth_mahadev_temple.jpg',
            'images/destination/rishikesh/riverrafting.jpg',
            'images/destination/rishikesh/triveni_ghat.jpg',
            'images/destination/rishikesh/the_beatles_ashram.jpeg',
            'images/destination/rishikesh/ram_jhula.jpg',
            'images/destination/rishikesh/parmarth_niketan.jpg'
        ],
        'festivals' => ['International Yoga Festival', 'Ganga Dussehra', 'Maha Shivaratri', 'Holi Festival', 'Diwali Festival', 'Kanwar Mela', 'Basant Panchami'],
        'cuisines' => ['Aloo Puri', 'Kachori', 'Chole Bhature', 'Lassi', 'Pahadi Thali', 'Samosa', 'Gulab Jamun'],
        'famous_spots' => ['The Beatles Ashram', 'Little Buddha Café', 'Ganga Beach', 'Café de Goa', 'Shivpuri Rafting Point', 'Trayambakeshwar Temple', 'Bairaj Lake'],
        'nearby' => ['Haridwar', 'Neelkanth Mahadev', 'Dehradun', 'Mussoorie', 'Shivpuri', 'Kanatal', 'Tehri'],
        'description' => 'Rishikesh, at the Ganges’ cleaner stretches, is the “Yoga Capital of the World,” buzzing with ashrams, meditation centers, and adventure sports. Lakshman Jhula’s swaying bridge connects vibrant markets, while Triveni Ghat’s evening Aarti enchants. The Beatles Ashram, where the band meditated, draws music fans, and rapids at Shivpuri thrill rafters. From Neelkanth Mahadev’s spiritual treks to riverside cafes serving global fare, Rishikesh offers a unique blend of serenity, adrenaline, and counterculture, perfect for yogis, adventurers, and soul-searchers.',
        'state_context' => 'Uttarakhand’s spiritual and adventure hub, Rishikesh, sits on the Ganges, blending yoga ashrams with rafting rapids. The state’s Himalayan foothills and sacred sites make it a global draw for seekers of peace and thrills, with Rishikesh as its vibrant epicenter.',
        'attractions_descriptions' => [
            'Lakshman Jhula is a famous suspension bridge with stunning river views.',
            'Neelkanth Mahadev Temple is a revered shrine dedicated to Lord Shiva.',
            'River Rafting offers thrilling experiences on the Ganges’ rapids.',
            'Triveni Ghat is a sacred bathing spot known for its evening Aarti.',
            'The Beatles Ashram showcases the band’s connection to Rishikesh.',
            'Ram Jhula is another iconic suspension bridge with scenic surroundings.',
            'Parmarth Niketan is a renowned ashram offering yoga and meditation.'
        ]
    ],
    [
        'name' => 'Tawang',
        'state' => 'Arunachal Pradesh',
        'budget' => 'Luxury',
        'type' => 'Offbeat',
        'duration' => 'Week-long',
        'image' => 'images/destination/tawang.jpg',
        'attractions' => ['Tawang Monastery', 'Sela Pass', 'Madhuri Lake', 'Nuranang Falls', 'Bum La Pass', 'Gorsam Chorten', 'Tawang War Memorial'],
        'attractions_images' => [
            'images/destination/tawang/tawang monastery.jpg',
            'images/destination/tawang/sela_pass.jpg',
            'images/destination/tawang/madhuri_lake.jpg',
            'images/destination/tawang/nuranang_falls.jpeg',
            'images/destination/tawang/bum_la_pass.jpg',
            'images/destination/tawang/gorsam_chorten.jpg',
            'images/destination/tawang/tawang_war_memorial.jpg'
        ],
        'festivals' => ['Torgya Festival', 'Losar Festival', 'Saka Dawa', 'Dukpa Tsheshi', 'Chokor Festival', 'Tawang Festival', 'Ganden Ngamchoe'],
        'cuisines' => ['Zan', 'Gyapa Khazi', 'Momos', 'Thukpa', 'Khura', 'Pika Pila', 'Lukter'],
        'famous_spots' => ['Tawang War Memorial', 'Craft Centre', 'Dragon Restaurant', 'PT Tso Lake', 'Sela Lake', 'Monpa Village', 'Tawang Market'],
        'nearby' => ['Bomdila', 'Zemithang', 'Dirang', 'Sangti Valley', 'Mandala Top', 'Thembang Village', 'Gorsam'],
        'description' => 'Tawang, at 3,048 meters, is a spiritual and scenic haven in Arunachal Pradesh, home to India’s largest Buddhist monastery, Tawang Monastery. Nestled near the Bhutan border, its Sela Pass and Madhuri Lake offer breathtaking vistas, while Nuranang Falls adds natural splendor. The Tawang War Memorial honors 1962 war heroes, and Bum La Pass thrills with its strategic allure. Tawang’s Monpa culture, vibrant festivals, and serene trails make it a paradise for those seeking solitude, history, and high-altitude adventure in a less-trodden corner of India.',
        'state_context' => 'Arunachal Pradesh, India’s easternmost state, is a land of misty mountains, tribal cultures, and Buddhist monasteries. Bordering Bhutan, China, and Myanmar, its rugged terrain and pristine rivers make Tawang a remote jewel for offbeat explorers.',
        'attractions_descriptions' => [ 
            'Tawang Monastery:** 400-year-old monastery with a giant Buddha statue.',  
           ' Sela Pass: Snowy pass at 4,170 meters with lakes and views.  ',
           ' Madhuri Lake:  Heart-shaped lake, named after a Bollywood shoot.  ',
           ' Nuranang Falls:  100-meter waterfall, also called Jang Falls.  ',
           ' Bum La Pass:  Indo-China border point, a thrilling excursion (permit re,quired).',  
           ' Gorsam Chorten:  Ancient stupa with Buddhist significance.  ',
           ' Tawang War Memorial:  Tribute to soldiers with a museum and flame. '
           ]
    ],
    [
        'name' => 'Mcleodganj',
        'state' => 'Himachal Pradesh',
        'budget' => 'Budget',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/mcleodganj.jpg',
        'attractions' => ['Triund Trek', 'Dalai Lama Temple', 'Bhagsu Waterfall', 'Namgyal Monastery', 'St. John in the Wilderness', 'Naddi View Point', 'Kangra Fort'],
        'attractions_images' => [
            'images/destination/mcleodganj/truind_trek.jpg',
            'images/destination/mcleodganj/dalai_lama_temple.jpg',
            'images/destination/mcleodganj/bhagsu_waterfall.jpeg',
            'images/destination/mcleodganj/namgyal_monastery.jpg',
            'images/destination/mcleodganj/st_john_in_the_wilderness.jpg',
            'images/destination/mcleodganj/naddi_view_point.jpg',
            'images/destination/mcleodganj/kangra_fort.jpg'
        ],
        'festivals' => ['Dal Festival', 'Losar Festival', 'Himalayan Festival', 'Holi Festival', 'Dharamshala Film Festival', 'Tibetan Uprising Day', 'Buddha Purnima'],
        'cuisines' => ['Tingmo', 'Thenthuk', 'Momos', 'Butter Tea', 'Shapale', 'Tsampa Porridge', 'Bhagsu Cake'],
        'famous_spots' => ['Illiterati Café', 'Norbulingka Institute', 'Tsuglagkhang Complex', 'Tibet Museum', 'Moonpeak Espresso', 'McLeod Ganj Market', 'Shiva Café'],
        'nearby' => ['Dharamkot', 'Bhagsu Nag', 'Kangra', 'Palampur', 'Kareri Lake', 'Billing', 'Masroor Temples'],
        'description' => 'Mcleodganj, at 2,082 meters, is the Dalai Lama’s home and a Tibetan cultural hub, often called “Little Lhasa.” Its Dalai Lama Temple and Namgyal Monastery pulse with Buddhist serenity, while Triund Trek offers jaw-dropping Himalayan views. Bhagsu Waterfall and St. John in the Wilderness add natural and colonial charm, and cafes like Illiterati serve global fare amidst mountain air. Mcleodganj’s vibrant markets, Tibetan handicrafts, and proximity to trekking routes make it a magnet for spiritual seekers, trekkers, and those craving a multicultural hill escape.',
        'state_context' => 'Himachal Pradesh’s Dhauladhar range cradles Mcleodganj, a Tibetan enclave with global appeal. The state’s blend of adventure, spirituality, and hill charm shines here, making it a cultural and natural retreat for diverse travelers.',
        'attractions_descriptions' => [
            'Triund Trek is a popular hike with stunning views of the Dhauladhar range.',
            'Dalai Lama Temple is the spiritual center of Tibetan Buddhism in India.',
            'Bhagsu Waterfall is a scenic spot for relaxation and photography.',
            'Namgyal Monastery is the largest Tibetan monastery outside Tibet.',
            'St. John in the Wilderness is a historic church set in a serene forest.',
            'Naddi View Point offers panoramic views of the Dhauladhar mountains.',
            'Kangra Fort is one of the oldest forts in India, rich in history.'
        ]
    ],
    [
        'name' => 'Chopta',
        'state' => 'Uttarakhand',
        'budget' => 'Budget',
        'type' => 'Offbeat',
        'duration' => '5-day',
        'image' => 'images/destination/chopta/chopta.jpg',
        'attractions' => ['Tungnath Temple', 'Deoria Tal', 'Chandrashila Trek', 'Kanchula Korak Musk Deer Sanctuary', 'Sari Village', 'Omkeshwar Temple', 'Ukhimath'],
        'attractions_images' => [
            'images/destination/chopta/tungnath.jpg',
            'images/destination/chopta/deoria_tal.jpeg',
            'images/destination/chopta/chandrashila_trek.jpg',
            'images/destination/chopta/kanchula_korak_musk_deer_sanctuary.jpg',
            'images/destination/chopta/sari_village.jpg',
            'images/destination/chopta/omkeshwar_temple.jpg',
            'images/destination/chopta/ukhimath.jpg'
        ],
        'festivals' => ['Makar Sankranti', 'Bikhauti Mela', 'Holi Festival', 'Diwali Festival', 'Nanda Devi Raj Jat', 'Butter Festival', 'Shivratri Festival'],
        'cuisines' => ['Chainsoo', 'Aloo Ke Gutke', 'Madua Roti', 'Kafuli', 'Phaanu', 'Jhangora Ki Kheer', 'Gahat Dal'],
        'famous_spots' => ['Local Campsites', 'Tungnath Café', 'Village Walks', 'Chopta Meadows', 'Anusuya Devi Temple', 'Kalimath Temple', 'Gopeshwar Market'],
        'nearby' => ['Rudraprayag', 'Ukhimath', 'Kedarnath', 'Guptkashi', 'Auli', 'Joshimath', 'Madmaheshwar'],
        'description' => 'Chopta, at 2,680 meters, is Uttarakhand’s “Mini Switzerland,” a serene base for treks to Tungnath and Chandrashila. Known for its meadows and Rhododendron blooms, it offers tranquility away from crowded hill stations. Tungnath, the highest Shiva temple, and Deoria Tal’s reflective lake captivate, while the Kanchula Korak Musk Deer Sanctuary showcases Himalayan wildlife. Chopta’s campsites, starry skies, and rustic villages like Sari make it a haven for nature lovers and trekkers seeking solitude and breathtaking vistas in an untouched Himalayan nook.',
        'state_context' => 'Uttarakhand’s Garhwal region, home to Chopta, is a trekker’s delight, with alpine meadows and sacred temples. The state’s spiritual rivers and rugged peaks create a backdrop for Chopta’s offbeat allure, drawing adventurers and pilgrims alike.',
        'attractions_descriptions' => [
            'Tungnath Temple is the highest Shiva temple, offering stunning views.',
            'Deoria Tal is a serene lake reflecting the surrounding mountains.',
            'Chandrashila Trek leads to a summit with panoramic Himalayan vistas.',
            'Kanchula Korak Musk Deer Sanctuary is home to diverse wildlife.',
            'Sari Village is a quaint village with beautiful landscapes.',
            'Omkeshwar Temple is a sacred shrine dedicated to Lord Shiva.',
            'Ukhimath is a small town known for its temples and scenic beauty.'
        ]
    ],
    [
        'name' => 'Meghamalai',
        'state' => 'Tamil Nadu',
        'budget' => 'Mid-range',
        'type' => 'Offbeat',
        'duration' => 'Weekend',
        'image' => 'images/destination/meghamalai.jpg',
        'attractions' => ['Highwavy Dam', 'Vellimalai', 'Suruli Falls', 'Meghamalai Wildlife Sanctuary', 'Manalar Falls', 'Maharaja Mettu', 'Thoovanam Falls'],
        'attractions_images' => [
            'images/destination/meghumalai/highwavy_dam.jpg',
            'images/destination/meghumalai/vellimalai.jpg',
            'images/destination/meghumalai/suruli_falls.jpg',
            'images/destination/meghumalai/meghamalai_wildlife_sanctuary.jpg',
            'images/destination/meghumalai/manalar_falls.jpg',
            'images/destination/meghumalai/maharaja_mettu.jpg',
            'images/destination/meghumalai/thoovanam_falls.jpg'
        ],
        'festivals' => ['Pongal', 'Chitra Pournami', 'Tamil New Year', 'Deepavali', 'Karthigai Deepam', 'Thaipusam', 'Aadi Perukku'],
        'cuisines' => ['Pongal', 'Chettinad Chicken', 'Meen Kuzhambu', 'Banana Bonda', 'Paruppu Vadai', 'Kambu Koozh', 'Pepper Rasam'],
        'famous_spots' => ['Tea Estates', 'Chellarkovil Viewpoint', 'Cloudlands Road', 'Meghamalai Viewpoint', 'Cardamom Plantations', 'Vattaparai Falls', 'Pothamedu'],
        'nearby' => ['Thekkady', 'Periyar Wildlife Sanctuary', 'Munnar', 'Kodaikanal', 'Madurai', 'Cumbum', 'Sabarimala'],
        'description' => 'Meghamalai, or “High Wavy Mountains,” at 1,500 meters, is Tamil Nadu’s hidden gem, draped in tea and cardamom estates. Tucked in the Western Ghats, it’s a paradise of rolling hills, waterfalls like Suruli and Manalar, and wildlife in Meghamalai Sanctuary. Highwavy Dam and Vellimalai’s viewpoints offer serene escapes, while Maharaja Mettu’s trails thrill trekkers. Less commercial than Ooty, Meghamalai’s misty trails, colonial-era bungalows, and spice-scented air attract offbeat travelers seeking solitude, nature, and a taste of Tamil Nadu’s highlands.',
        'state_context' => 'Tamil Nadu, South India’s cultural powerhouse, blends ancient temples, coastal beauty, and lush hills. Meghamalai, in its Western Ghats, showcases the state’s quieter side, with tea estates and misty peaks complementing its Dravidian heritage.',
        'attractions_descriptions' => [ 
            'Highwavy Dam: Scenic reservoir amidst tea gardens, great for picnics.', 
            'Vellimalai: Highest peak with panoramic Ghats views.  ',
            'Suruli Falls: 150-ft waterfall, ideal for nature walks.  ',
            'Meghamalai Wildlife Sanctuary: Home to elephants, leopards, and birds.',
            'Manalar Falls: Secluded cascade in dense forests.  ',
            'Maharaja Mettu: Trekking spot with valley vistas.  ',
            'Thoovanam Falls: Lesser-known falls, perfect for quiet retreats.'
            
        ],
    ],
    [
        'name' => 'Spiti Valley',
        'state' => 'Himachal Pradesh',
        'budget' => 'Luxury',
        'type' => 'Offbeat',
        'duration' => 'Week-long',
        'image' => 'images/destination/spiti_valley.jpg',
        'attractions' => ['Key Monastery', 'Chandratal Lake', 'Pin Valley National Park', 'Tabo Monastery', 'Dhankar Monastery', 'Kibber Village', 'Langza Buddha Statue'],
        'attractions_images' => [
            'images/destination/spiti/key_monastery.jpg',
            'images/destination/spiti/chandratal_lake.jpg',
            'images/destination/spiti/pin_valley_national_park.jpg',
            'images/destination/spiti/tabo_monastery.jpg',
            'images/destination/spiti/dhankar_monastery.jpg',
            'images/destination/spiti/kibber_village.jpg',
            'images/destination/spiti/langza_buddha_statue.jpg'
        ],
        'festivals' => ['Gustor Festival', 'Tribal Fair', 'Ladarcha Fair', 'Tsuglagan Festival', 'Chakhar Festival', 'Fagli Festival', 'Losar Festival'],
        'cuisines' => ['Thukpa', 'Chhang', 'Momos', 'Butter Tea', 'Tsampa', 'Siddu', 'Paba'],
        'famous_spots' => ['Kaza Market', 'The Himalayan Café', 'Spiti River Walk', 'Hikkim Post Office', 'Komik Village', 'Dhankar Lake', 'Mud Village'],
        'nearby' => ['Tabo', 'Langza', 'Komic', 'Kaza', 'Hikkim', 'Dhankar', 'Nako'],
        'description' => 'Spiti Valley, meaning “Middle Land” between India and Tibet, is a high-altitude desert with surreal beauty. Key Monastery and Tabo Monastery, over 1,000 years old, anchor its spiritual landscape, while Chandratal Lake’s turquoise waters mesmerize. Villages like Kibber and Langza, home to the giant Buddha statue, offer homestay warmth, and Pin Valley National Park shelters snow leopards. Spiti’s rugged roads, fossil trails, and clear skies (ideal for astrophotography) attract bikers, trekkers, and those seeking raw, untouched nature and Buddhist tranquility.',
        'state_context' => 'Himachal Pradesh’s Spiti Valley, a remote desert region, is a land of stark beauty and ancient monasteries. Its high-altitude landscapes and Tibetan culture create a unique travel experience, attracting adventurers and spiritual seekers alike.',
        'attractions_descriptions' => [
            'Key Monastery is a stunning hilltop monastery with panoramic views.',
            'Chandratal Lake is a crescent-shaped lake known for its blue waters.',
            'Pin Valley National Park is home to diverse wildlife and stunning landscapes.',
            'Tabo Monastery is a UNESCO World Heritage site with ancient murals.',
            'Dhankar Monastery is perched on a cliff, offering breathtaking views.',
            'Kibber Village is one of the highest inhabited villages in the world.',
            'Langza Buddha Statue is a giant statue overlooking the valley.'
        ]
    ],
    [
        'name' => 'Ziro Valley',
        'state' => 'Arunachal Pradesh',
        'budget' => 'Mid-range',
        'type' => 'Offbeat',
        'duration' => '5-day',
        'image' => 'images/destination/ziro_valley.jpg',
        'attractions' => ['Talley Valley', 'Kile Pakho', 'Ziro Puto', 'Shivling at Siddeshwar Nath', 'Meghna Cave Temple', 'Pine Grove', 'Dolo Mando'],
        'attractions_images' => [
            'images/destination/ziro valley/talley_valley.jpg',
            'images/destination/ziro valley/kile_pakho.jpg',
            'images/destination/ziro valley/ziro_puto.jpg',
            'images/destination/ziro valley/shivling_at_siddeshwar_nath.jpg',
            'images/destination/ziro valley/meghna_cave_temple.jpg',
            'images/destination/ziro valley/pine_grove.jpg',
            'images/destination/ziro valley/dolo_mando.jpg'
        ],
        'festivals' => ['Ziro Music Festival', 'Dree Festival', 'Myoko Festival', 'Nyokum Festival', 'Siang River Festival', 'Boori Boot Festival', 'Solung Festival'],
        'cuisines' => ['Pika Pila', 'Bamboo Shoot Curry', 'Apong', 'Fish Stew', 'Lukter', 'Pe Hak', 'Dung Po'],
        'famous_spots' => ['Tarin Fish Farm', 'Ziro Pine Grove', 'Hapoli Market', 'Rice Fields', 'Hong Village', 'Ziro Church', 'Pine Bamboo Restaurant'],
        'nearby' => ['Itanagar', 'Daporijo', 'Along', 'Pasighat', 'Tuting', 'Majuli', 'Yingkiong'],
        'description' => 'Ziro Valley, at 1,700 meters, is a breathtaking expanse of rice fields, pine groves, and Apatani villages, framed by misty hills. Home to the Apatani tribe, known for sustainable farming and facial tattoos (a fading tradition), Ziro is a UNESCO tentative World Heritage Site for its cultural landscape. Attractions like Talley Valley’s biodiversity and Ziro Puto’s panoramic views enchant nature lovers, while the Ziro Music Festival draws global artists and travelers. With serene trails, homestays, and local brews like Apong, Ziro offers an offbeat escape for those seeking tranquility, tribal culture, and vibrant festivals in Arunachal’s heart.',
        'state_context' => 'Arunachal Pradesh, India’s easternmost state, is a tapestry of tribal cultures, Himalayan peaks, and pristine valleys. Bordering Bhutan, China, and Myanmar, its rugged terrain and biodiversity make it a haven for adventurers and cultural explorers. Ziro Valley, in the Lower Subansiri district, showcases the state’s serene beauty and Apatani tribal heritage, offering a glimpse into a world where tradition and nature coexist harmoniously.',
        'attractions_descriptions' => [
            'Talley Valley is a biodiversity hotspot with lush forests and wildlife.',
            'Kile Pakho offers panoramic views of the valley and surrounding hills.',
            'Ziro Puto is a hilltop offering stunning views of the Ziro Valley.',
            'Shivling at Siddeshwar Nath is a sacred site with a unique rock formation.',
            'Meghna Cave Temple is an ancient temple with beautiful rock carvings.',
            'Pine Grove is a serene area with tall pine trees and scenic beauty.',
            'Dolo Mando is a hilltop offering breathtaking views of the valley.'
        ]
    ],
    [
        'name' => 'Auli',
        'state' => 'Uttarakhand',
        'budget' => 'Mid-range',
        'type' => 'Adventure',
        'duration' => '5-day',
        'image' => 'images/destination/auli/auli.jpg',
        'attractions' => ['Skiing Slopes', 'Gurso Bugyal', 'Joshimath', 'Nanda Devi National Park', 'Auli Ropeway', 'Chattrakund Lake', 'Vishnuprayag'],
        'attractions_images' => [
            'images/destination/auli/skiing_slopes.jpg',
            'images/destination/auli/gurso_bugyal.jpg',
            'images/destination/auli/joshimath.jpg',
            'images/destination/auli/nanda_devi_national_park.jpg',
            'images/destination/auli/auli_ropeway.jpg',
            'images/destination/auli/chattrakund_lake.jpg',
            'images/destination/auli/vishnuprayag.jpg'
        ],
        'festivals' => ['Winter Carnival', 'Basant Panchami', 'Makar Sankranti', 'Nanda Devi Festival', 'Holi Festival', 'Diwali Festival', 'Shivratri Festival'],
        'cuisines' => ['Chainsoo', 'Gahat Dal', 'Aloo Ke Gutke', 'Bal Mithai', 'Kafuli', 'Jhangora Ki Kheer', 'Singori'],
        'famous_spots' => ['Ski Resorts', 'Auli Chair Lift', 'Joshimath Market', 'Narsingh Temple', 'Auli Lake', 'Chenab Lake', 'Kwani Bugyal'],
        'nearby' => ['Valley of Flowers', 'Badrinath', 'Hemkund Sahib', 'Mana Village', 'Tapkeshwar', 'Kedarnath', 'Chamoli'],
        'description' => 'Auli, at 2,800 meters, is India’s premier skiing destination, often compared to Swiss Alps for its powdery slopes and pine-fringed meadows. Perched above Joshimath, it boasts panoramic views of Nanda Devi, India’s second-highest peak. The Auli Ropeway, one of Asia’s longest, connects to Gurso Bugyal’s grasslands, while Chattrakund Lake’s turquoise waters add charm. Winter brings skiers, and summer attracts trekkers to Nanda Devi National Park. With cozy resorts, spiritual vibes from nearby Badrinath, and crisp mountain air, Auli is a year-round delight for adventure seekers and nature lovers.',
        'state_context' => 'Uttarakhand, the “Land of Gods,” is a Himalayan haven of pilgrimage sites, adventure trails, and alpine meadows. Auli, in the Garhwal region, is its winter sports capital, offering snow-clad slopes and serene vistas, complementing the state’s spiritual and natural allure.',
        'attractions_descriptions' => [
            'Skiing Slopes are perfect for winter sports enthusiasts.',
            'Gurso Bugyal is a beautiful meadow with stunning views.',
            'Joshimath is a historic town and base for Auli.',
            'Nanda Devi National Park is a UNESCO World Heritage site.',
            'Auli Ropeway offers breathtaking views of the Himalayas.',
            'Chattrakund Lake is a serene lake surrounded by forests.',
            'Vishnuprayag is the confluence of Alaknanda and Dhauliganga rivers.'
        ]
    ],
    [
        'name' => 'Gokarna',
        'state' => 'Karnataka',
        'budget' => 'Budget',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/gokarna/gokarna.jpg',
        'attractions' => ['Om Beach', 'Kudle Beach', 'Mahabaleshwar Temple', 'Half Moon Beach', 'Gokarna', 'Gokarna Main Beach', 'Yana Caves'],
        'attractions_images' => [
            'images/destination/gokarna/om_beach.jpg',
            'images/destination/gokarna/kudle_beach.jpg',
            'images/destination/gokarna/mahabaleshwar_temple.jpg',
            'images/destination/gokarna/half_moon_beach.jpg',
            'images/destination/gokarna/gokarna.jpg',
            'images/destination/gokarna/gokarna_main_beach.png',
            'images/destination/gokarna/yana_caves.jpg'
        ],
        'festivals' => ['Shivaratri Festival', 'Gokarna Beach Festival', 'Holi Festival', 'Ganesh Chaturthi', 'Deepavali', 'Ugadi Festival', 'Vittala Purnima'],
        'cuisines' => ['Neer Dosa', 'Kane Rava Fry', 'Fish Curry', 'Banana Buns', 'Bangude Pulimunchi', 'Chicken Sukka', 'Mysore Pak'],
        'famous_spots' => ['Namaste Café', 'Half Moon Beach', 'Mirjan Fort', 'Prema Restaurant', 'Gokarna Cliffs', 'Sunset Point', 'Shri Hari Café'],
        'nearby' => ['Murudeshwar', 'Yana Caves', 'Karwar', 'Ankola', 'Dandeli', 'Udupi', 'Honnavar'],
        'description' => 'Gokarna, a coastal town at 10 meters above sea level, is Karnataka’s hidden gem, blending spirituality with laid-back beach vibes. Unlike Goa’s crowds, its Om Beach, Kudle Beach, and Half Moon Beach offer tranquility, with golden sands and turquoise waves. The Mahabaleshwar Temple, a Shiva shrine, attracts devotees, while Yana Caves add adventure. Gokarna’s shacks, like Namaste Café, serve fresh seafood, and its cliffs and sunsets inspire wanderers. Ideal for budget travelers, it’s a perfect mix of pilgrimage, surfing, and chilling by the sea, steeped in coastal Karnataka’s charm.',
        'state_context' => 'Karnataka, South India’s dynamic state, blends tech hubs, ancient ruins, and coastal beauty. Gokarna, on its Arabian Sea shore, is a serene counterpoint to Karnataka’s bustling cities, offering beaches and temples that draw pilgrims and beachcombers alike.',
        'attractions_descriptions' => [
            'Om Beach is famous for its unique shape resembling the Om symbol.',
            'Kudle Beach is a serene beach perfect for relaxation and sunsets.',
            'Mahabaleshwar Temple is a revered Hindu temple dedicated to Lord Shiva.',
            'Half Moon Beach is a secluded beach accessible by boat or trek.',
            'Gokarna Main Beach is the town’s main beach, lively and vibrant.',
            'Yana Caves are unique rock formations and trekking spots.'
        ]
    ],
    [
        'name' => 'Coorg',
        'state' => 'Karnataka',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/coorg.jpg',
        'attractions' => ['Abbey Falls', 'Mandalpatti', 'Dubare Elephant Camp', 'Talacauvery', 'Raja’s Seat', 'Iruppu Falls', 'Nagarhole National Park'],
        'attractions_images' => [
            'images/destination/coorg/abbey_falls.jpg',
            'images/destination/coorg/mandalpatti.jpg',
            'images/destination/coorg/dubare_elephant_camp.jpg',
            'images/destination/coorg/talacauvery.jpg',
            'images/destination/coorg/rajas_seat.jpg',
            'images/destination/coorg/iruppu_falls.jpg',
            'images/destination/coorg/nagarhole_national_park.jpg'
        ],
        'festivals' => ['Puthari Festival', 'Kailpodh Festival', 'Madikeri Dasara', 'Holi Festival', 'Deepavali', 'Tula Sankramana', 'Coorg Food Festival'],
        'cuisines' => ['Pandi Curry', 'Kadambuttu', 'Noolputtu', 'Coorgi Style Chicken Curry', 'Bamboo Shoot Curry', 'Akki Roti', 'Koli Curry'],
        'famous_spots' => ['Raja’s Seat', 'Namdroling Monastery', 'Coorg Cuisine', 'Madikeri Fort', 'Coffee Plantations', 'Tadiandamol Peak', 'Omkareshwara Temple'],
        'nearby' => ['Nagarhole', 'Madikeri', 'Mysore', 'Wayanad', 'Mangalore', 'Kushalnagar', 'Kabini'],
        'description' => 'Coorg, or Kodagu, at 1,500 meters, is Karnataka’s “Scotland of India,” blanketed in coffee plantations, misty hills, and waterfalls like Abbey Falls. Known for its warrior Kodava community, it blends rugged charm with cozy homestays. Attractions like Mandalpatti’s viewpoints and Talacauvery, the Cauvery River’s source, captivate, while Dubare Elephant Camp offers unique wildlife encounters. Coorg’s spicy cuisine, vibrant festivals, and treks to Tadiandamol Peak make it a haven for nature lovers, foodies, and those seeking a cultural immersion in Karnataka’s green heart.',
        'state_context' => 'Karnataka’s Western Ghats cradle Coorg, a lush hill region famed for coffee and Kodava culture. The state’s blend of heritage sites, like Hampi, and natural escapes, like Coorg, makes it a diverse draw, with Coorg offering a refreshing contrast to urban Bangalore.',
        'attractions_descriptions' => [
            'Abbey Falls is a picturesque waterfall surrounded by coffee plantations.',
            'Mandalpatti offers stunning panoramic views of the Western Ghats.',
            'Dubare Elephant Camp is a unique experience to interact with elephants.',
            'Talacauvery is the origin of the Cauvery River, with scenic beauty.',
            'Raja’s Seat is a viewpoint with beautiful sunset views.',
            'Iruppu Falls is a serene waterfall ideal for nature lovers.',
            'Nagarhole National Park is a wildlife sanctuary known for its biodiversity.'
        ]
    ],
    [
        'name' => 'Andaman & Nicobar',
        'state' => 'Andaman & Nicobar',
        'budget' => 'Luxury',
        'type' => 'Adventure',
        'duration' => 'Week-long',
        'image' => 'images/destination/andaman n nico/andaman_nicobar.jpg',
        'attractions' => ['Havelock Island', 'Radhanagar Beach', 'Cellular Jail', 'Neil Island', 'Ross Island', 'Barren Island', 'Elephant Beach'],
        'attractions_images' => [
            'images/destination/andaman n nico/havelock_island.jpg',
            'images/destination/andaman n nico/radhanagar_beach.jpg',
            'images/destination/andaman n nico/cellular_jail.jpg',
            'images/destination/andaman n nico/neil_island.jpg',
            'images/destination/andaman n nico/ross_island.jpg',
            'images/destination/andaman n nico/barren_island.jpg',
            'images/destination/andaman n nico/elephant_beach.png'
        ],
        'festivals' => ['Island Tourism Festival', 'Subhash Mela', 'Andaman Marathon', 'Monsoon Music Festival', 'Diwali Festival', 'Beach Festival', 'Film Festival'],
        'cuisines' => ['Fish Curry', 'Grilled Lobster', 'Prawn Masala', 'Coconut Prawn Curry', 'Chilli Crab', 'Tandoori Fish', 'Amritsari Kulcha'],
        'famous_spots' => ['SeaShell Bar & Lounge', 'Corbyn’s Cove', 'Aberdeen Bazaar', 'Viper Island', 'Samudrika Museum', 'Chatham Saw Mill', 'Marina Park'],
        'nearby' => ['Neil Island', 'Baratang Island', 'Diglipur', 'Little Andaman', 'Rangat', 'Long Island', 'Mayabunder'],
        'description' => 'Andaman & Nicobar, a cluster of 572 islands, is a turquoise haven where adventure meets serenity. Havelock Island’s Radhanagar Beach, voted Asia’s best, stuns with its sands, while Cellular Jail in Port Blair narrates India’s freedom struggle. Snorkeling at Elephant Beach, exploring Ross Island’s ruins, and visiting active volcano Barren Island thrill explorers. Neil Island’s coral reefs and laid-back vibe enchant, and the islands’ seafood, vibrant markets, and festivals like the Island Tourism Festival add flavor. Perfect for luxury seekers, it’s a scuba diver’s, historian’s, and beach lover’s utopia.',
        'state_context' => 'The Andaman & Nicobar Islands, a Union Territory in the Bay of Bengal, are India’s tropical paradise, with coral reefs, white beaches, and dense jungles. Far from the mainland, their tribal heritage and colonial past create a unique blend, making them a dream for adventure and relaxation.',
        'attractions_descriptions' => [
            'Havelock Island is known for its stunning beaches and water sports.',
            'Radhanagar Beach is famous for its pristine sands and sunsets.',
            'Cellular Jail is a historical site with a poignant history.',
            'Neil Island is known for its coral reefs and tranquil beaches.',
            'Ross Island has ruins of British colonial buildings.',
            'Barren Island is home to India’s only active volcano.',
            'Elephant Beach is famous for snorkeling and water sports.'
        ]
    ],
    [
        'name' => 'Darjeeling',
        'state' => 'West Bengal',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/darjeeling.jpg',
        'attractions' => ['Tiger Hill', 'Batasia Loop', 'Darjeeling Himalayan Railway', 'Padmaja Naidu Himalayan Zoo', 'Peace Pagoda', 'Ghoom Monastery', 'Rock Garden'],
        'attractions_images' => [
            'images/destination/darjeeling/tiger_hill.jpg',
            'images/destination/darjeeling/batasia_loop.jpg',
            'images/destination/darjeeling/darjeeling_himalayan_railway.jpg',
            'images/destination/darjeeling/padmaja_naidu_himalayan_zoo.jpg',
            'images/destination/darjeeling/peace_pagoda.jpg',
            'images/destination/darjeeling/ghoom_monastery.jpg',
            'images/destination/darjeeling/rock_garden.jpg'
        ],
        'festivals' => ['Darjeeling Carnival', 'Losar Festival', 'Teej Festival', 'Durga Puja', 'Holi Festival', 'Orange Festival', 'Tea Festival'],
        'cuisines' => ['Thukpa', 'Momos', 'Sel Roti', 'Churpee Soup', 'Aloo Dum', 'Gundruk', 'Sael Roti'],
        'famous_spots' => ['Glenary’s Bakery', 'Chowrasta', 'Japanese Peace Pagoda', 'Tea Gardens', 'Mall Road', 'Keventer’s Café', 'Himalayan Mountaineering Institute'],
        'nearby' => ['Kalimpong', 'Mirik', 'Kurseong', 'Gangtok', 'Pelling', 'Lava', 'Sikkim'],
        'description' => 'Darjeeling, at 2,050 meters, is India’s “Queen of Hills,” famed for its tea estates and Himalayan vistas, including Kanchenjunga’s peaks. The UNESCO-listed Darjeeling Himalayan Railway, or Toy Train, chugs through misty slopes, while Tiger Hill’s sunrise mesmerizes. Batasia Loop’s war memorial and Peace Pagoda’s serenity add depth, and the Padmaja Naidu Zoo showcases Himalayan wildlife. With colonial-era cafes like Glenary’s, vibrant Chowrasta markets, and festivals like the Tea Festival, Darjeeling blends nostalgia, nature, and culture, enchanting tea lovers and romantics alike.',
        'state_context' => 'West Bengal, a cultural mosaic, spans Kolkata’s urban buzz to Darjeeling’s Himalayan calm. Known for tea gardens and Bengali heritage, the state’s northern hills, where Darjeeling lies, offer cool climes and colonial charm, making it a timeless retreat.',
        'attractions_descriptions' => [
            'Tiger Hill is famous for its stunning sunrise views over Kanchenjunga.',
            'Batasia Loop is a unique railway loop with a war memorial.',
            'Darjeeling Himalayan Railway is a UNESCO World Heritage site.',
            'Padmaja Naidu Himalayan Zoo is home to rare Himalayan species.',
            'Peace Pagoda offers panoramic views and tranquility.',
            'Ghoom Monastery is one of the oldest Tibetan monasteries in the region.',
            'Rock Garden is a beautiful garden with waterfalls and scenic views.'
        ]
    ],
    [
        'name' => 'Lonavala & Khandala',
        'state' => 'Maharashtra',
        'budget' => 'Budget',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/lonavala_khandala.jpg',
        'attractions' => ['Tiger’s Leap', 'Bhushi Dam', 'Rajmachi Fort', 'Karla Caves', 'Lohagad Fort', 'Pawna Lake', 'Duke’s Nose'],
        'attractions_images' => [
            'images/destination/lonavala/tigers_leap.jpg',
            'images/destination/lonavala/bhushi_dam.jpeg',
            'images/destination/lonavala/rajmachi.jpg',
            'images/destination/lonavala/karla_caves.jpg',
            'images/destination/lonavala/lohagad_fort.jpg',
            'images/destination/lonavala/pawna_lake.jpg',
            'images/destination/lonavala/dukes_nose.jpg'
        ],
        'festivals' => ['Ganesh Chaturthi', 'Diwali Trekking Events', 'Monsoon Festival', 'Holi Festival', 'Shivratri Festival', 'Khandala Food Festival', 'Pawna Camping Festival'],
        'cuisines' => ['Vada Pav', 'Misal Pav', 'Chikki', 'Puran Poli', 'Pav Bhaji', 'Sabudana Vada', 'Bhel Puri'],
        'famous_spots' => ['Cooper’s Chikki', 'Lion’s Point', 'German Bakery', 'Kune Falls', 'Sunset Point', 'Della Adventure Park', 'Wax Museum'],
        'nearby' => ['Karla Caves', 'Pawna Lake', 'Maval', 'Kamshet', 'Talegaon', 'Khopoli', 'Igatpuri'],
        'description' => 'Lonavala and Khandala, at 620 meters, are Maharashtra’s beloved monsoon getaways, just 80 km from Mumbai. Nestled in the Sahyadri hills, they boast misty valleys, waterfalls like Bhushi Dam, and forts like Rajmachi. Tiger’s Leap’s cliff views and Pawna Lake’s camping draw crowds, while Karla Caves’ Buddhist rock-cut shrines add history. Famous for Lonavala’s chikki (nut brittle), cozy cafes, and treks to Duke’s Nose, these towns offer a refreshing blend of nature, adventure, and nostalgia, perfect for weekenders seeking a quick hill retreat.',
        'state_context' => 'Maharashtra, India’s economic powerhouse, blends Mumbai’s urban pulse with Western Ghats’ greenery. Lonavala and Khandala, twin hill stations, offer a quick escape from city life, showcasing the state’s knack for balancing modernity with nature’s tranquility.',
        'attractions_descriptions' => [
            'Tiger’s Leap is a cliff with stunning views and a waterfall.',
            'Bhushi Dam is a popular picnic spot during the monsoon.',
            'Rajmachi Fort offers trekking opportunities and scenic views.',
            'Karla Caves are ancient rock-cut Buddhist caves.',
            'Lohagad Fort is a historic fort with panoramic views.',
            'Pawna Lake is perfect for camping and water sports.',
            'Duke’s Nose is a trekking spot with breathtaking views.'
        ]
    ],
    [
        'name' => 'Mahabaleshwar',
        'state' => 'Maharashtra',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/mahabaleshwar.jpg',
        'attractions' => ['Elephant’s Head Point', 'Venna Lake', 'Pratapgad Fort', 'Mapro Garden', 'Lingmala Falls', 'Wilson Point', 'Kate’s Point'],
        'attractions_images' => [
            'images/destination/mahabaleshwar/elephants_head_point.jpg',
            'images/destination/mahabaleshwar/venna_lake.jpg',
            'images/destination/mahabaleshwar/pratapgad_fort.jpg',
            'images/destination/mahabaleshwar/mapro_garden.jpg',
            'images/destination/mahabaleshwar/lingmala_falls.jpg',
            'images/destination/mahabaleshwar/wilson_point.jpg',
            'images/destination/mahabaleshwar/kates_point.jpg'
        ],
        'festivals' => ['Strawberry Festival', 'Holi Celebration', 'Ganesh Chaturthi', 'Diwali Festival', 'Monsoon Festival', 'Shivratri Festival', 'Mahabaleshwar Fair'],
        'cuisines' => ['Strawberries with Cream', 'Puran Poli', 'Bhakri', 'Kanda Bhaji', 'Misal Pav', 'Corn Patties', 'Pav Bhaji'],
        'famous_spots' => ['Mapro Garden', 'Lingmala Falls', 'Venna Lake Boating', 'Arthur’s Seat', 'Sunset Point', 'Strawberry Farms', 'Mahabaleshwar Temple'],
        'nearby' => ['Panchgani', 'Tapola', 'Wai', 'Satara', 'Raigad', 'Pratapgad', 'Kaas Plateau'],
        'description' => 'Mahabaleshwar, at 1,353 meters, is Maharashtra’s summer capital, famed for juicy strawberries, misty valleys, and viewpoints like Elephant’s Head Point. Venna Lake’s boating and Mapro Garden’s strawberry shakes delight families, while Pratapgad Fort narrates Maratha history. Lingmala Falls’ cascades and Wilson Point’s sunrises enchant, and the town’s temples, like Mahabaleshwar Temple, add spiritual depth. With horse rides, cozy cafes, and treks to Kate’s Point, it’s a perfect weekend escape for Mumbaikars and Punekars craving nature, food, and cool mountain air.',
        'state_context' => 'Maharashtra’s Western Ghats shine in Mahabaleshwar, a hill station blending colonial charm with strawberry fields. The state’s coastal and hilly diversity, from Konkan beaches to Sahyadri peaks, makes Mahabaleshwar a refreshing retreat for urban dwellers.',
        'attractions_descriptions' => [
            'Elephant’s Head Point offers stunning views of the valley.',
            'Venna Lake is perfect for boating and picnics.',
            'Pratapgad Fort is a historic fort with panoramic views.',
            'Mapro Garden is famous for strawberries and delicious treats.',
            'Lingmala Falls is a beautiful waterfall ideal for nature lovers.',
            'Wilson Point is the highest point in Mahabaleshwar with sunrise views.',
            'Kate’s Point offers breathtaking views of the surrounding hills.'
        ]
    ],
    [
        'name' => 'Tirthan Valley',
        'state' => 'Himachal Pradesh',
        'budget' => 'Budget',
        'type' => 'Offbeat',
        'duration' => '5-day',
        'image' => 'images/destination/tirthan_valley.jpg',
        'attractions' => ['Great Himalayan National Park', 'Serolsar Lake', 'Jalori Pass', 'Chhoie Waterfall', 'Tirthan River', 'Lambri Village', 'Raghupur Fort'],
        'attractions_images' => [
            'images/destination/tirthan valleyu/great_himalayan_national_park.jpg',
            'images/destination/tirthan valleyu/serolsar_lake.jpg',
            'images/destination/tirthan valleyu/jalori_pass.jpg',
            'images/destination/tirthan valleyu/chhoie_waterfall.jpg',
            'images/destination/tirthan valleyu/tirthan_river.jpg',
            'images/destination/tirthan valleyu/lambri_village.jpg',
            'images/destination/tirthan valleyu/raghupur_fort.jpg'
        ],
        'festivals' => ['Fagli Festival', 'Holi Festival', 'Kullu Dussehra', 'Losar Festival', 'Sazo Festival', 'Baisakhi Festival', 'Tirthan Fish Festival'],
        'cuisines' => ['Siddu', 'Chana Madra', 'Bhatura', 'Rajma Chawal', 'Lingdi Aloo', 'Kullu Trout', 'Babru'],
        'famous_spots' => ['Raju’s Cottage', 'Gushaini Trails', 'River Crossing Camps', 'Trout Fishing Spots', 'Banjar Market', 'Sai Ropa', 'Sojha Village'],
        'nearby' => ['Shoja', 'Jibhi', 'Manali', 'Kullu', 'Aut', 'Banjar', 'Mandi'],
        'description' => 'Tirthan Valley, at 1,600 meters, is a hidden paradise named after the Tirthan River, flowing from the Great Himalayan National Park (GHNP), a UNESCO site. Ideal for anglers (trout fishing), trekkers (Serolsar Lake),PURPLE and campers, it offers serene trails to Jalori Pass and Chhoie Waterfall. Villages like Lambri exude rustic charm, and Raghupur Fort’s ruins add history. With eco-lodges, starry skies, and no urban clutter, Tirthan is a haven for nature lovers, digital nomads, and those seeking quiet Himalayan solitude, enriched by local Pahadi culture.',
        'state_context' => 'Himachal Pradesh’s lesser-known Tirthan Valley, in the Kullu district, epitomizes the state’s serene side, far from crowded Manali. Its rivers, forests, and Himalayan peaks offer an offbeat escape, blending adventure with untouched natural beauty.',
        'attractions_descriptions' => [
            'Great Himalayan National Park is a UNESCO World Heritage site.',
            'Serolsar Lake is a serene lake surrounded by lush forests.',
            'Jalori Pass offers stunning views and trekking opportunities.',
            'Chhoie Waterfall is a beautiful waterfall ideal for picnics.',
            'Tirthan River is perfect for trout fishing and river activities.',
            'Lambri Village is a quaint village with traditional architecture.',
            'Raghupur Fort offers panoramic views of the valley.'
        ]
    ],
    [
        'name' => 'Puducherry',
        'state' => 'Puducherry',
        'budget' => 'Mid-range',
        'type' => 'Party',
        'duration' => 'Weekend',
        'image' => 'images/destination/puducherry.jpg',
        'attractions' => ['Promenade Beach', 'Auroville', 'Paradise Beach', 'Sri Aurobindo Ashram', 'French Quarter', 'Puducherry Museum', 'Botanical Garden'],
        'attractions_images' => [
            'images/destination/puducherry/promanade_beach.jpg',
            'images/destination/puducherry/auroville.jpg',
            'images/destination/puducherry/paradise_beach.jpg',
            'images/destination/puducherry/sri_aurobindo_ashram.jpg',
            'images/destination/puducherry/french_quarter.jpg',
            'images/destination/puducherry/puducherry_museum.jpg',
            'images/destination/puducherry/botanical_garden.jpg'
        ],
        'festivals' => ['Bastille Day', 'Pondicherry Heritage Festival', 'Pongal Festival', 'Deepavali', 'French Food Festival', 'Yoga Festival', 'Masi Magam'],
        'cuisines' => ['Creole Curries', 'Baguettes', 'Seafood Vindaloo', 'Stuffed Crab', 'Prawn Balchao', 'Mutton Korma', 'Pain au Chocolat'],
        'famous_spots' => ['Café Des Arts', 'White Town', 'Rock Beach', 'Le Café', 'Serenity Beach', 'Goubert Market', 'La Maison Rose'],
        'nearby' => ['Auroville', 'Paradise Beach', 'Chidambaram', 'Mahabalipuram', 'Kanchipuram', 'Pichavaram Mangroves', 'Tharangambadi'],
        'description' => 'Puducherry, or Pondicherry, at sea level, is a charming coastal town where French boulevards meet Tamil vibrancy. White Town’s pastel villas and Promenade Beach’s waves create a relaxed vibe, while Auroville’s Matrimandir draws spiritual seekers. Sri Aurobindo Ashram offers meditative calm, and Paradise Beach’s sands invite lounging. With French cafes, vibrant markets, and festivals like Bastille Day, Puducherry is a party destination with soul, ideal for couples, foodies, and those craving a blend of cultures, beaches, and quirky history on India’s east coast.',
        'state_context' => 'Puducherry, a Union Territory on India’s Coromandel Coast, is a former French colony with a unique blend of Tamil and European cultures. Its palm-fringed beaches, colonial villas, and spiritual communes like Auroville make it a quirky coastal escape, distinct from mainland India.',
        'attractions_descriptions' => [
            'Promenade Beach is a popular beach with a scenic promenade.',
            'Auroville is an experimental township promoting peace and unity.',
            'Paradise Beach is known for its pristine sands and tranquility.',
            'Sri Aurobindo Ashram is a spiritual community founded by Sri Aurobindo.',
            'French Quarter showcases colonial architecture and vibrant streets.',
            'Puducherry Museum exhibits the region’s history and culture.',
            'Botanical Garden is a serene garden with diverse flora.'
        ] 
    ],
];

return $destinations;

