<?php

$destinations = [
    [
        'name' => 'Srinagar',
        'state' => 'Jammu & Kashmir',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/srinagar.jpg',
        'attractions' => ['Dal Lake', 'Mughal Gardens', 'Shankaracharya Temple'],
        'attractions_images' => [
            'images/destination/dal_lake.jpg',
            'images/destination/mughal_gardens.jpg',
            'images/destination/shankaracharya_temple.jpg'
        ],
        'festivals' => ['Tulip Festival', 'Shikara Festival'],
        'cuisines' => ['Rogan Josh', 'Dum Aloo', 'Kahwa', 'Yakhni'],
        'famous_spots' => ['Shikara Ride at Dal Lake', 'Floating Market', 'Café de Linz'],
        'nearby' => ['Gulmarg', 'Sonamarg'],
    ],
    [
        'name' => 'Leh-Ladakh',
        'state' => 'Jammu & Kashmir',
        'budget' => 'Luxury',
        'type' => 'Adventure',
        'duration' => 'Week-long',
        'image' => 'images/destination/leh_ladakh.jpg',
        'attractions' => ['Pangong Lake', 'Magnetic Hill', 'Thiksey Monastery'],
        'attractions_images' => [
            'images/destination/pangong_lake.jpg',
            'images/destination/magnetic_hill.jpg',
            'images/destination/thiksey_monastery.jpg'
        ],
        'festivals' => ['Hemis Festival', 'Losar Festival'],
        'cuisines' => ['Thukpa', 'Momos', 'Skyu', 'Butter Tea'],
        'famous_spots' => ['Leh Market', 'Leh Palace', 'German Bakery'],
        'nearby' => ['Nubra Valley', 'Tso Moriri Lake'],
    ],
    [
        'name' => 'Shimla',
        'state' => 'Himachal Pradesh',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/shimla.jpg',
        'attractions' => ['The Ridge', 'Mall Road', 'Jakhu Temple'],
        'attractions_images' => [
            'images/destination/the_ridge.jpg',
            'images/destination/mall_road.jpg',
            'images/destination/jakhu_temple.jpg'
        ],
        'festivals' => ['Summer Festival', 'Ice Skating Carnival'],
        'cuisines' => ['Chana Madra', 'Siddu', 'Babru', 'Himachali Trout'],
        'famous_spots' => ['Scandal Point', 'Indian Coffee House', 'Christ Church'],
        'nearby' => ['Kufri', 'Chail'],
    ],
    [
        'name' => 'Manali',
        'state' => 'Himachal Pradesh',
        'budget' => 'Mid-range',
        'type' => 'Adventure',
        'duration' => '5-day',
        'image' => 'images/destination/manali.jpg',
        'attractions' => ['Solang Valley', 'Hadimba Temple', 'Rohtang Pass'],
        'attractions_images' => [
            'images/destination/solang_valley.jpg',
            'images/destination/hadimba_temple.jpg',
            'images/destination/rohtang_pass.jpg'
        ],
        'festivals' => ['Dussehra Festival', 'Winter Carnival'],
        'cuisines' => ['Siddu', 'Trout Fish', 'Babru', 'Mittha'],
        'famous_spots' => ['Old Manali Cafes', 'Manali Club House', 'Manu Temple'],
        'nearby' => ['Naggar', 'Kasol'],
    ],
    [
        'name' => 'Nainital',
        'state' => 'Uttarakhand',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/nainital.jpg',
        'attractions' => ['Naini Lake', 'Snow View Point', 'Naina Devi Temple'],
        'attractions_images' => [
            'images/destination/naini_lake.jpg',
            'images/destination/snow_view_point.jpg',
            'images/destination/naina_devi_temple.jpg'
        ],
        'festivals' => ['Nanda Devi Fair', 'Autumn Festival'],
        'cuisines' => ['Aloo Ke Gutke', 'Bhatt Ki Churkani', 'Bal Mithai', 'Ras Bhaat'],
        'famous_spots' => ['Café Lakeside', 'Tiffin Top', 'Nainital Zoo'],
        'nearby' => ['Bhimtal', 'Naukuchiatal'],
    ],
    [
        'name' => 'Gangtok',
        'state' => 'Sikkim',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/gangtok.jpg',
        'attractions' => ['Tsomgo Lake', 'Rumtek Monastery', 'Nathula Pass'],
        'attractions_images' => [
            'images/destination/tsomgo_lake.jpg',
            'images/destination/rumtek_monastery.jpg',
            'images/destination/nathula_pass.jpg'
        ],
        'festivals' => ['Losar Festival', 'Saga Dawa Festival'],
        'cuisines' => ['Phagshapa', 'Thukpa', 'Momos', 'Sel Roti'],
        'famous_spots' => ['MG Marg', 'Baker’s Café', 'Flower Exhibition Centre'],
        'nearby' => ['Namchi', 'Pelling'],
    ],
    [
        'name' => 'Shillong',
        'state' => 'Meghalaya',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/shillong.jpg',
        'attractions' => ['Elephant Falls', 'Umiam Lake', 'Shillong Peak'],
        'attractions_images' => [
            'images/destination/elephant_falls.jpg',
            'images/destination/umiam_lake.jpg',
            'images/destination/shillong_peak.jpg'
        ],
        'festivals' => ['Shad Suk Mynsiem', 'Wangala Festival'],
        'cuisines' => ['Jadoh', 'Dohneiiong', 'Tungrymbai', 'Pukhlein'],
        'famous_spots' => ['Café Shillong', 'Don Bosco Museum', 'Police Bazar'],
        'nearby' => ['Cherrapunji', 'Mawlynnong'],
    ],
    [
        'name' => 'Kaziranga',
        'state' => 'Assam',
        'budget' => 'Mid-range',
        'type' => 'Adventure',
        'duration' => '5-day',
        'image' => 'images/destination/kaziranga.jpg',
        'attractions' => ['Elephant Safaris', 'Jeep Safari', 'Tea Gardens'],
        'attractions_images' => [
            'images/destination/elephant_safaris.jpg',
            'images/destination/jeep_safari.jpg',
            'images/destination/tea_gardens.jpg'
        ],
        'festivals' => ['Bihu Festival', 'Kaziranga Elephant Festival'],
        'cuisines' => ['Masor Tenga', 'Khar', 'Duck Meat Curry', 'Pitika'],
        'famous_spots' => ['Kaziranga Orchid Park', 'Local Tea Gardens', 'Ethnic Village Restaurant'],
        'nearby' => ['Majuli', 'Tezpur'],
    ],
    [
        'name' => 'Jaipur',
        'state' => 'Rajasthan',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/jaipur.jpg',
        'attractions' => ['Hawa Mahal', 'Amber Fort', 'City Palace'],
        'attractions_images' => [
            'images/destination/hawa_mahal.jpg',
            'images/destination/amber_fort.jpg',
            'images/destination/city_palace.jpg'
        ],
        'festivals' => ['Jaipur Literature Festival', 'Teej Festival'],
        'cuisines' => ['Dal Baati Churma', 'Laal Maas', 'Ghewar', 'Ker Sangri'],
        'famous_spots' => ['Patrika Gate', 'Masala Chowk', 'Albert Hall Museum'],
        'nearby' => ['Ajmer', 'Pushkar'],
    ],
    [
        'name' => 'Varanasi',
        'state' => 'Uttar Pradesh',
        'budget' => 'Budget',
        'type' => 'Spiritual',
        'duration' => '5-day',
        'image' => 'images/destination/varanasi.jpg',
        'attractions' => ['Kashi Vishwanath Temple', 'Dashashwamedh Ghat', 'Sarnath'],
        'attractions_images' => [
            'images/destination/kashi_vishwanath_temple.jpg',
            'images/destination/dashashwamedh_ghat.jpg',
            'images/destination/sarnath.jpg'
        ],
        'festivals' => ['Dev Deepawali', 'Ganga Mahotsav'],
        'cuisines' => ['Kachori Sabzi', 'Tamatar Chaat', 'Baati Chokha', 'Malaiyo'],
        'famous_spots' => ['Blue Lassi Shop', 'Assi Ghat', 'Banaras Hindu University'],
        'nearby' => ['Sarnath', 'Allahabad'],
    ],
    [
        'name' => 'Kasol',
        'state' => 'Himachal Pradesh',
        'budget' => 'Budget',
        'type' => 'Offbeat',
        'duration' => 'Weekend',
        'image' => 'images/destination/kasol.jpg',
        'attractions' => ['Parvati Valley', 'Kheerganga Trek', 'Manikaran Sahib'],
        'attractions_images' => [
            'images/destination/parvati_valley.jpg',
            'images/destination/kheerganga_trek.jpg',
            'images/destination/manikaran_sahib.jpg'
        ],
        'festivals' => ['Indrasan Festival', 'Himalayan Music Festival'],
        'cuisines' => ['Israeli Salad', 'Shakshuka', 'Tandoori Trout', 'Falafel'],
        'famous_spots' => ['Moon Dance Café', 'Jim Morrison Café', 'Tosh Village'],
        'nearby' => ['Malana', 'Manikaran'],
    ],
    [
        'name' => 'Rishikesh',
        'state' => 'Uttarakhand',
        'budget' => 'Budget',
        'type' => 'Spiritual',
        'duration' => '5-day',
        'image' => 'images/destination/rishikesh.jpg',
        'attractions' => ['Lakshman Jhula', 'Neelkanth Mahadev Temple', 'River Rafting'],
        'attractions_images' => [
            'images/destination/lakshman_jhula.jpg',
            'images/destination/neelkanth_mahadev_temple.jpg',
            'images/destination/river_rafting.jpg'
        ],
        'festivals' => ['International Yoga Festival', 'Ganga Dussehra'],
        'cuisines' => ['Aloo Puri', 'Kachori', 'Chole Bhature', 'Lassi'],
        'famous_spots' => ['The Beatles Ashram', 'Little Buddha Café', 'Ganga Beach'],
        'nearby' => ['Haridwar', 'Neelkanth Mahadev'],
    ],
    [
        'name' => 'Tawang',
        'state' => 'Arunachal Pradesh',
        'budget' => 'Luxury',
        'type' => 'Offbeat',
        'duration' => 'Week-long',
        'image' => 'images/destination/tawang.jpg',
        'attractions' => ['Tawang Monastery', 'Sela Pass', 'Madhuri Lake'],
        'attractions_images' => [
            'images/destination/tawang_monastery.jpg',
            'images/destination/sela_pass.jpg',
            'images/destination/madhuri_lake.jpg'
        ],
        'festivals' => ['Torgya Festival', 'Losar Festival'],
        'cuisines' => ['Zan', 'Gyapa Khazi', 'Momos', 'Thukpa'],
        'famous_spots' => ['Tawang War Memorial', 'Craft Centre', 'Dragon Restaurant'],
        'nearby' => ['Bomdila', 'Zemithang'],
    ],
    [
        'name' => 'Mcleodganj',
        'state' => 'Himachal Pradesh',
        'budget' => 'Budget',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/mcleodganj.jpg',
        'attractions' => ['Triund Trek', 'Dalai Lama Temple', 'Bhagsu Waterfall'],
        'attractions_images' => [
            'images/destination/triund_trek.jpg',
            'images/destination/dalai_lama_temple.jpg',
            'images/destination/bhagsu_waterfall.jpg'
        ],
        'festivals' => ['Dal Festival', 'Losar Festival'],
        'cuisines' => ['Tingmo', 'Thenthuk', 'Momos', 'Butter Tea'],
        'famous_spots' => ['Illiterati Café', 'Norbulingka Institute', 'Tsuglagkhang Complex'],
        'nearby' => ['Dharamkot', 'Bhagsu Nag'],
    ],
    [
        'name' => 'Chopta',
        'state' => 'Uttarakhand',
        'budget' => 'Budget',
        'type' => 'Offbeat',
        'duration' => '5-day',
        'image' => 'images/destination/chopta.jpg',
        'attractions' => ['Tungnath Temple', 'Deoria Tal', 'Chandrashila Trek'],
        'attractions_images' => [
            'images/destination/tungnath_temple.jpg',
            'images/destination/deoria_tal.jpg',
            'images/destination/chandrashila_trek.jpg'
        ],
        'festivals' => ['Makar Sankranti', 'Bikhauti Mela'],
        'cuisines' => ['Chainsoo', 'Aloo Ke Gutke', 'Madua Roti', 'Kafuli'],
        'famous_spots' => ['Local Campsites', 'Tungnath Café', 'Village Walks'],
        'nearby' => ['Rudraprayag', 'Ukhimath'],
    ],
    [
        'name' => 'Meghamalai',
        'state' => 'Tamil Nadu',
        'budget' => 'Mid-range',
        'type' => 'Offbeat',
        'duration' => 'Weekend',
        'image' => 'images/destination/meghamalai.jpg',
        'attractions' => ['Highwavy Dam', 'Vellimalai', 'Suruli Falls'],
        'attractions_images' => [
            'images/destination/highwavy_dam.jpg',
            'images/destination/vellimalai.jpg',
            'images/destination/suruli_falls.jpg'
        ],
        'festivals' => ['Pongal', 'Chitra Pournami'],
        'cuisines' => ['Pongal', 'Chettinad Chicken', 'Meen Kuzhambu', 'Banana Bonda'],
        'famous_spots' => ['Tea Estates', 'Chellarkovil Viewpoint', 'Cloudlands Road'],
        'nearby' => ['Thekkady', 'Periyar Wildlife Sanctuary'],
    ],
    [
        'name' => 'Spiti Valley',
        'state' => 'Himachal Pradesh',
        'budget' => 'Luxury',
        'type' => 'Offbeat',
        'duration' => 'Week-long',
        'image' => 'images/destination/spiti_valley.jpg',
        'attractions' => ['Key Monastery', 'Chandratal Lake', 'Pin Valley National Park'],
        'attractions_images' => [
            'images/destination/key_monastery.jpg',
            'images/destination/chandratal_lake.jpg',
            'images/destination/pin_valley_national_park.jpg'
        ],
        'festivals' => ['Gustor Festival', 'Tribal Fair'],
        'cuisines' => ['Thukpa', 'Chhang', 'Momos', 'Butter Tea'],
        'famous_spots' => ['Kaza Market', 'The Himalayan Café', 'Spiti River Walk'],
        'nearby' => ['Tabo', 'Langza', 'Komic'],
    ],
    [
        'name' => 'Ziro Valley',
        'state' => 'Arunachal Pradesh',
        'budget' => 'Mid-range',
        'type' => 'Offbeat',
        'duration' => '5-day',
        'image' => 'images/destination/ziro_valley.jpg',
        'attractions' => ['Talley Valley', 'Kile Pakho', 'Ziro Puto'],
        'attractions_images' => [
            'images/destination/talley_valley.jpg',
            'images/destination/kile_pakho.jpg',
            'images/destination/ziro_puto.jpg'
        ],
        'festivals' => ['Ziro Music Festival', 'Dree Festival'],
        'cuisines' => ['Pika Pila', 'Bamboo Shoot Curry', 'Apong', 'Fish Stew'],
        'famous_spots' => ['Tarin Fish Farm', 'Ziro Pine Grove', 'Hapoli Market'],
        'nearby' => ['Itanagar', 'Daporijo'],
    ],
    [
        'name' => 'Auli',
        'state' => 'Uttarakhand',
        'budget' => 'Mid-range',
        'type' => 'Adventure',
        'duration' => '5-day',
        'image' => 'images/destination/auli.jpg',
        'attractions' => ['Skiing Slopes', 'Gurso Bugyal', 'Joshimath'],
        'attractions_images' => [
            'images/destination/skiing_slopes.jpg',
            'images/destination/gurso_bugyal.jpg',
            'images/destination/joshimath.jpg'
        ],
        'festivals' => ['Winter Carnival', 'Basant Panchami'],
        'cuisines' => ['Chainsoo', 'Gahat Dal', 'Aloo Ke Gutke', 'Bal Mithai'],
        'famous_spots' => ['Ski Resorts', 'Auli Chair Lift', 'Joshimath Market'],
        'nearby' => ['Valley of Flowers', 'Badrinath'],
    ],
    [
        'name' => 'Gokarna',
        'state' => 'Karnataka',
        'budget' => 'Budget',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/gokarna.jpg',
        'attractions' => ['Om Beach', 'Kudle Beach', 'Mahabaleshwar Temple'],
        'attractions_images' => [
            'images/destination/om_beach.jpg',
            'images/destination/kudle_beach.jpg',
            'images/destination/mahabaleshwar_temple.jpg'
        ],
        'festivals' => ['Shivaratri Festival', 'Gokarna Beach Festival'],
        'cuisines' => ['Neer Dosa', 'Kane Rava Fry', 'Fish Curry', 'Banana Buns'],
        'famous_spots' => ['Namaste Café', 'Half Moon Beach', 'Mirjan Fort'],
        'nearby' => ['Murudeshwar', 'Yana Caves'],
    ],
    [
        'name' => 'Coorg',
        'state' => 'Karnataka',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/coorg.jpg',
        'attractions' => ['Abbey Falls', 'Mandalpatti', 'Dubare Elephant Camp'],
        'attractions_images' => [
            'images/destination/abbey_falls.jpg',
            'images/destination/mandalpatti.jpg',
            'images/destination/dubare_elephant_camp.jpg'
        ],
        'festivals' => ['Puthari Festival', 'Kailpodh Festival'],
        'cuisines' => ['Pandi Curry', 'Kadambuttu', 'Noolputtu', 'Coorgi Style Chicken Curry'],
        'famous_spots' => ['Raja’s Seat', 'Namdroling Monastery', 'Coorg Cuisine'],
        'nearby' => ['Nagarhole', 'Madikeri'],
    ],
    [
        'name' => 'Andaman & Nicobar',
        'state' => 'Andaman & Nicobar',
        'budget' => 'Luxury',
        'type' => 'Adventure',
        'duration' => 'Week-long',
        'image' => 'images/destination/andaman_nicobar.jpg',
        'attractions' => ['Havelock Island', 'Radhanagar Beach', 'Cellular Jail'],
        'attractions_images' => [
            'images/destination/havelock_island.jpg',
            'images/destination/radhanagar_beach.jpg',
            'images/destination/cellular_jail.jpg'
        ],
        'festivals' => ['Island Tourism Festival', 'Subhash Mela'],
        'cuisines' => ['Fish Curry', 'Grilled Lobster', 'Prawn Masala', 'Coconut Prawn Curry'],
        'famous_spots' => ['SeaShell Bar & Lounge', 'Corbyn’s Cove', 'Aberdeen Bazaar'],
        'nearby' => ['Neil Island', 'Baratang Island'],
    ],
    [
        'name' => 'Darjeeling',
        'state' => 'West Bengal',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/darjeeling.jpg',
        'attractions' => ['Tiger Hill', 'Batasia Loop', 'Darjeeling Himalayan Railway'],
        'attractions_images' => [
            'images/destination/tiger_hill.jpg',
            'images/destination/batasia_loop.jpg',
            'images/destination/darjeeling_himalayan_railway.jpg'
        ],
        'festivals' => ['Darjeeling Carnival', 'Losar Festival'],
        'cuisines' => ['Thukpa', 'Momos', 'Sel Roti', 'Churpee Soup'],
        'famous_spots' => ['Glenary’s Bakery', 'Chowrasta', 'Japanese Peace Pagoda'],
        'nearby' => ['Kalimpong', 'Mirik'],
    ],
    [
        'name' => 'Lonavala & Khandala',
        'state' => 'Maharashtra',
        'budget' => 'Budget',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/lonavala_khandala.jpg',
        'attractions' => ['Tiger’s Leap', 'Bhushi Dam', 'Rajmachi Fort'],
        'attractions_images' => [
            'images/destination/tigers_leap.jpg',
            'images/destination/bhushi_dam.jpg',
            'images/destination/rajmachi_fort.jpg'
        ],
        'festivals' => ['Ganesh Chaturthi', 'Diwali Trekking Events'],
        'cuisines' => ['Vada Pav', 'Misal Pav', 'Chikki', 'Puran Poli'],
        'famous_spots' => ['Cooper’s Chikki', 'Lion’s Point', 'German Bakery'],
        'nearby' => ['Karla Caves', 'Pawna Lake'],
    ],
    [
        'name' => 'Mahabaleshwar',
        'state' => 'Maharashtra',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/mahabaleshwar.jpg',
        'attractions' => ['Elephant’s Head Point', 'Venna Lake', 'Pratapgad Fort'],
        'attractions_images' => [
            'images/destination/elephants_head_point.jpg',
            'images/destination/venna_lake.jpg',
            'images/destination/pratapgad_fort.jpg'
        ],
        'festivals' => ['Strawberry Festival', 'Holi Celebration'],
        'cuisines' => ['Strawberries with Cream', 'Puran Poli', 'Bhakri', 'Kanda Bhaji'],
        'famous_spots' => ['Mapro Garden', 'Lingmala Falls', 'Venna Lake Boating'],
        'nearby' => ['Panchgani', 'Tapola'],
    ],
    [
        'name' => 'Tirthan Valley',
        'state' => 'Himachal Pradesh',
        'budget' => 'Budget',
        'type' => 'Offbeat',
        'duration' => '5-day',
        'image' => 'images/destination/tirthan_valley.jpg',
        'attractions' => ['Great Himalayan National Park', 'Serolsar Lake', 'Jalori Pass'],
        'attractions_images' => [
            'images/destination/great_himalayan_national_park.jpg',
            'images/destination/serolsar_lake.jpg',
            'images/destination/jalori_pass.jpg'
        ],
        'festivals' => ['Fagli Festival', 'Holi Festival'],
        'cuisines' => ['Siddu', 'Chana Madra', 'Bhatura', 'Rajma Chawal'],
        'famous_spots' => ['Raju’s Cottage', 'Gushaini Trails', 'River Crossing Camps'],
        'nearby' => ['Shoja', 'Jibhi'],
    ],
    [
        'name' => 'Puducherry',
        'state' => 'Puducherry',
        'budget' => 'Mid-range',
        'type' => 'Party',
        'duration' => 'Weekend',
        'image' => 'images/destination/puducherry.jpg',
        'attractions' => ['Promenade Beach', 'Auroville', 'Paradise Beach'],
        'attractions_images' => [
            'images/destination/promenade_beach.jpg',
            'images/destination/auroville.jpg',
            'images/destination/paradise_beach.jpg'
        ],
        'festivals' => ['Bastille Day', 'Pondicherry Heritage Festival'],
        'cuisines' => ['Creole Curries', 'Baguettes', 'Seafood Vindaloo', 'Stuffed Crab'],
        'famous_spots' => ['Café Des Arts', 'White Town', 'Rock Beach'],
        'nearby' => ['Auroville', 'Paradise Beach'],
    ],
];

return $destinations;