<?php

$destinations = [
    [
        'name' => 'Srinagar',
        'state' => 'Jammu & Kashmir',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/srinagar.jpg',
        'attractions' => ['Dal Lake', 'Mughal Gardens', 'Shankaracharya Temple', 'Hazratbal Shrine', 'Nishat Bagh', 'Chashme Shahi', 'Pari Mahal'],
        'attractions_images' => [
            'images/destination/srinagar/dal_lake.jpg',
            'images/destination/srinagar/mughal_gardens.jpg',
            'images/destination/srinagar/shankaracharya_temple.jpg',
            'images/destination/srinagar/hazratbal_shrine.jpg',
            'images/destination/srinagar/nishat_bagh.jpg',
            'images/destination/srinagar/chashme_shahi.jpg',
            'images/destination/srinagar/pari_mahal.jpg'
        ],
        'festivals' => ['Tulip Festival', 'Shikara Festival', 'Srinagar Festival', 'Navroz', 'Urs of Sheikh Nooruddin', 'Baisakhi', 'Saffron Festival'],
        'cuisines' => ['Rogan Josh', 'Dum Aloo', 'Kahwa', 'Yakhni', 'Gushtaba', 'Nadir Monji', 'Haaq'],
        'famous_spots' => ['Shikara Ride at Dal Lake', 'Floating Market', 'Café de Linz', 'Shalimar Bagh', 'Khanqah-e-Moula', 'Char Chinar', 'Harwan Garden'],
        'nearby' => ['Gulmarg', 'Sonamarg', 'Pahalgam', 'Yusmarg', 'Dachigam National Park', 'Aru Valley', 'Betaab Valley'],
    ],
    [
        'name' => 'Leh-Ladakh',
        'state' => 'Jammu & Kashmir',
        'budget' => 'Luxury',
        'type' => 'Adventure',
        'duration' => 'Week-long',
        'image' => 'images/destination/leh_ladakh.jpg',
        'attractions' => ['Pangong Lake', 'Magnetic Hill', 'Thiksey Monastery', 'Nubra Valley', 'Hemis Monastery', 'Shanti Stupa', 'Zanskar Valley'],
        'attractions_images' => [
            'images/destination/leh-ladakh/pangong_lake.jpg',
            'images/destination/leh-ladakh/magnetic_hill.jpg',
            'images/destination/leh-ladakh/thiksey_monastery.jpg',
            'images/destination/leh-ladakh/nubra_valley.jpg',
            'images/destination/leh-ladakh/hemis_monastery.jpg',
            'images/destination/leh-ladakh/shanti_stupa.jpg',
            'images/destination/leh-ladakh/zanskar_valley.jpg'
        ],
        'festivals' => ['Hemis Festival', 'Losar Festival', 'Ladakh Festival', 'Sindhu Darshan', 'Thiksey Gustor', 'Spituk Gustor', 'Dosmoche Festival'],
        'cuisines' => ['Thukpa', 'Momos', 'Skyu', 'Butter Tea', 'Chhutagi', 'Paba', 'Tingmo'],
        'famous_spots' => ['Leh Market', 'Leh Palace', 'German Bakery', 'Hall of Fame', 'Sangam (Confluence)', 'Diskit Monastery', 'Tso Kar Lake'],
        'nearby' => ['Nubra Valley', 'Tso Moriri Lake', 'Kargil', 'Alchi', 'Lamayuru', 'Stok Village', 'Dras'],
    ],
    [
        'name' => 'Shimla',
        'state' => 'Himachal Pradesh',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/shimla.jpg',
        'attractions' => ['The Ridge', 'Mall Road', 'Jakhu Temple', 'Viceregal Lodge', 'Christ Church', 'Annandale', 'Kali Bari Temple'],
        'attractions_images' => [
            'images/destination/shimla/the_ridge.jpg',
            'images/destination/shimla/mall_road.jpg',
            'images/destination/shimla/jakhu_temple.jpg',
            'images/destination/shimla/viceregal_lodge.jpg',
            'images/destination/shimla/christ_church.jpg',
            'images/destination/shimla/annandale.jpg',
            'images/destination/shimla/kali_bari_temple.jpg'
        ],
        'festivals' => ['Summer Festival', 'Ice Skating Carnival', 'Shimla Winter Carnival', 'Baisakhi Mela', 'Lavi Fair', 'Holi Festival', 'Christmas Celebrations'],
        'cuisines' => ['Chana Madra', 'Siddu', 'Babru', 'Himachali Trout', 'Dham', 'Patande', 'Sepu Vadi'],
        'famous_spots' => ['Scandal Point', 'Indian Coffee House', 'Christ Church', 'Lakkar Bazaar', 'Green Valley', 'Toy Train Ride', 'State Museum'],
        'nearby' => ['Kufri', 'Chail', 'Narkanda', 'Mashobra', 'Fagu', 'Tattapani', 'Naldehra'],
    ],
    [
        'name' => 'Manali',
        'state' => 'Himachal Pradesh',
        'budget' => 'Mid-range',
        'type' => 'Adventure',
        'duration' => '5-day',
        'image' => 'images/destination/manali.jpg',
        'attractions' => ['Solang Valley', 'Hadimba Temple', 'Rohtang Pass', 'Vashisht Hot Springs', 'Manu Temple', 'Jogini Falls', 'Beas Kund'],
        'attractions_images' => [
            'images/destination/manali/solang_valley.jpg',
            'images/destination/manali/hadimba_temple.jpg',
            'images/destination/manali/rohtang_pass.jpg',
            'images/destination/manali/vashisht_hot_springs.jpg',
            'images/destination/manali/manu_temple.jpg',
            'images/destination/manali/jogini_falls.jpg',
            'images/destination/manali/beas_kund.jpg'
        ],
        'festivals' => ['Dussehra Festival', 'Winter Carnival', 'Kullu Dussehra', 'Hadimba Devi Fair', 'Spring Festival', 'Holi Festival', 'Losar Festival'],
        'cuisines' => ['Siddu', 'Trout Fish', 'Babru', 'Mittha', 'Dham', 'Chana Madra', 'Kullu Puti'],
        'famous_spots' => ['Old Manali Cafes', 'Manali Club House', 'Manu Temple', 'Tibetan Monastery', 'Naggar Castle', 'Van Vihar', 'Mall Road'],
        'nearby' => ['Naggar', 'Kasol', 'Kullu', 'Manikaran', 'Rohtang La', 'Parvati Valley', 'Sissu'],
    ],
    [
        'name' => 'Nainital',
        'state' => 'Uttarakhand',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/nainital.jpg',
        'attractions' => ['Naini Lake', 'Snow View Point', 'Naina Devi Temple', 'Tiffin Top', 'Eco Cave Gardens', 'High Altitude Zoo', 'Naina Peak'],
        'attractions_images' => [
            'images/destination/nainital/naini_lake.jpg',
            'images/destination/nainital/snow_view_point.jpg',
            'images/destination/nainital/naina_devi_temple.jpg',
            'images/destination/nainital/tiffin_top.jpg',
            'images/destination/nainital/eco_cave_gardens.jpg',
            'images/destination/nainital/high_altitude_zoo.jpg',
            'images/destination/nainital/naina_peak.jpg'
        ],
        'festivals' => ['Nanda Devi Fair', 'Autumn Festival', 'Phool Dei', 'Holi Festival', 'Diwali Mela', 'Sharadotsav', 'Uttarayani Fair'],
        'cuisines' => ['Aloo Ke Gutke', 'Bhatt Ki Churkani', 'Bal Mithai', 'Ras Bhaat', 'Kafuli', 'Singori', 'Phaanu'],
        'famous_spots' => ['Café Lakeside', 'Tiffin Top', 'Nainital Zoo', 'Mall Road', 'Governor’s House', 'St. John’s Church', 'Hanuman Garhi'],
        'nearby' => ['Bhimtal', 'Naukuchiatal', 'Sattal', 'Ranikhet', 'Almora', 'Mukteshwar', 'Kausani'],
    ],
    [
        'name' => 'Gangtok',
        'state' => 'Sikkim',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/gangtok.jpg',
        'attractions' => ['Tsomgo Lake', 'Rumtek Monastery', 'Nathula Pass', 'Enchey Monastery', 'Ban Jhakri Falls', 'Hanuman Tok', 'Do-Drul Chorten'],
        'attractions_images' => [
            'images/destination/gangtok/tsomgo_lake.jpg',
            'images/destination/gangtok/rumtek_monastery.jpg',
            'images/destination/gangtok/nathula_pass.jpg',
            'images/destination/gangtok/enchey_monastery.jpg',
            'images/destination/gangtok/ban_jhakri_falls.jpg',
            'images/destination/gangtok/hanuman_tok.jpg',
            'images/destination/gangtok/do-drul_chorten.jpg'
        ],
        'festivals' => ['Losar Festival', 'Saga Dawa Festival', 'Pang Lhabsol', 'Dasain Festival', 'Tihar Festival', 'Bumchu Festival', 'Drukpa Tsheshi'],
        'cuisines' => ['Phagshapa', 'Thukpa', 'Momos', 'Sel Roti', 'Gundruk', 'Sinki Soup', 'Chhurpi'],
        'famous_spots' => ['MG Marg', 'Baker’s Café', 'Flower Exhibition Centre', 'Tashi View Point', 'Gangtok Ropeway', 'Sikkim Himalayan Zoo', 'Café Live & Loud'],
        'nearby' => ['Namchi', 'Pelling', 'Ravangla', 'Yuksom', 'Lachung', 'Lachen', 'Zuluk'],
    ],
    [
        'name' => 'Shillong',
        'state' => 'Meghalaya',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/shillong.jpg',
        'attractions' => ['Elephant Falls', 'Umiam Lake', 'Shillong Peak', 'Ward’s Lake', 'Lady Hydari Park', 'Laitlum Canyons', 'Cathedral of Mary'],
        'attractions_images' => [
            'images/destination/shillong/elephant_falls.jpg',
            'images/destination/shillong/umiam_lake.jpg',
            'images/destination/shillong/shillong_peak.jpg',
            'images/destination/shillong/wards_lake.jpg',
            'images/destination/shillong/lady_hydari_park.jpg',
            'images/destination/shillong/laitlum_canyons.jpg',
            'images/destination/shillong/cathedral_of_mary.jpg'
        ],
        'festivals' => ['Shad Suk Mynsiem', 'Wangala Festival', 'Nongkrem Dance Festival', 'Behdienkhlam Festival', 'Strawberry Festival', 'Christmas Festival', 'Meghalaya Day'],
        'cuisines' => ['Jadoh', 'Dohneiiong', 'Tungrymbai', 'Pukhlein', 'Nakham Bitchi', 'Pumaloi', 'Dohjem'],
        'famous_spots' => ['Café Shillong', 'Don Bosco Museum', 'Police Bazar', 'Mawjymbuin Cave', 'Air Force Museum', 'All Saints Cathedral', 'Butterfly Museum'],
        'nearby' => ['Cherrapunji', 'Mawlynnong', 'Dawki', 'Mawsynram', 'Nongpoh', 'Jowai', 'Nartiang'],
    ],
    [
        'name' => 'Kaziranga',
        'state' => 'Assam',
        'budget' => 'Mid-range',
        'type' => 'Adventure',
        'duration' => '5-day',
        'image' => 'images/destination/kaziranga.jpg',
        'attractions' => ['Elephant Safaris', 'Jeep Safari', 'Tea Gardens', 'Kaziranga Orchid Park', 'Panbari Reserve', 'Kakochang Falls', 'Deopahar Ruins'],
        'attractions_images' => [
            'images/destination/kaziranga/elephant_safaris.jpg',
            'images/destination/kaziranga/jeep_safari.jpg',
            'images/destination/kaziranga/tea_gardens.jpg',
            'images/destination/kaziranga/kaziranga_orchid_park.jpg',
            'images/destination/kaziranga/panbari_reserve.jpg',
            'images/destination/kaziranga/kakochang_falls.jpg',
            'images/destination/kaziranga/deopahar_ruins.jpg'
        ],
        'festivals' => ['Bihu Festival', 'Kaziranga Elephant Festival', 'Tea Festival', 'Ambubachi Mela', 'Dehing Patkai Festival', 'Ras Mahotsav', 'Majuli Festival'],
        'cuisines' => ['Masor Tenga', 'Khar', 'Duck Meat Curry', 'Pitika', 'Pork Anishi', 'Aloo Pitika', 'Ou Tenga'],
        'famous_spots' => ['Kaziranga Orchid Park', 'Local Tea Gardens', 'Ethnic Village Restaurant', 'Hathikuli Tea Estate', 'Brahmaputra River Bank', 'Kohora Village', 'Rangmon Bird Watching'],
        'nearby' => ['Majuli', 'Tezpur', 'Jorhat', 'Sivsagar', 'Dibrugarh', 'Golaghat', 'Hoollongapar Gibbon Sanctuary'],
    ],
    [
        'name' => 'Jaipur',
        'state' => 'Rajasthan',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/jaipur.jpg',
        'attractions' => ['Hawa Mahal', 'Amber Fort', 'City Palace', 'Jantar Mantar', 'Nahargarh Fort', 'Jaigarh Fort', 'Albert Hall Museum'],
        'attractions_images' => [
            'images/destination/jaipur/hawa_mahal.jpg',
            'images/destination/jaipur/amber_fort.jpg',
            'images/destination/jaipur/city_palace.jpg',
            'images/destination/jaipur/jantar_mantar.jpg',
            'images/destination/jaipur/nahargarh_fort.jpg',
            'images/destination/jaipur/jaigarh_fort.jpg',
            'images/destination/jaipur/albert_hall_museum.jpg'
        ],
        'festivals' => ['Jaipur Literature Festival', 'Teej Festival', 'Diwali Festival', 'Gangaur Festival', 'Kite Festival', 'Elephant Festival', 'Pushkar Fair'],
        'cuisines' => ['Dal Baati Churma', 'Laal Maas', 'Ghewar', 'Ker Sangri', 'Pyaaz Kachori', 'Mawa Kachori', 'Rajasthani Thali'],
        'famous_spots' => ['Patrika Gate', 'Masala Chowk', 'Albert Hall Museum', 'Chokhi Dhani', 'Jal Mahal', 'Hathi Gaon', 'Bapu Bazaar'],
        'nearby' => ['Ajmer', 'Pushkar', 'Alwar', 'Ranthambore', 'Neemrana', 'Bharatpur', 'Tonk'],
    ],
    [
        'name' => 'Varanasi',
        'state' => 'Uttar Pradesh',
        'budget' => 'Budget',
        'type' => 'Spiritual',
        'duration' => '5-day',
        'image' => 'images/destination/varanasi.jpg',
        'attractions' => ['Kashi Vishwanath Temple', 'Dashashwamedh Ghat', 'Sarnath', 'Assi Ghat', 'Manikarnika Ghat', 'Ramnagar Fort', 'Bharat Mata Temple'],
        'attractions_images' => [
            'images/destination/varanasi/kashi_vishwanath_temple.jpg',
            'images/destination/varanasi/dashashwamedh_ghat.jpg',
            'images/destination/varanasi/sarnath.jpg',
            'images/destination/varanasi/assi_ghat.jpg',
            'images/destination/varanasi/manikarnika_ghat.jpg',
            'images/destination/varanasi/ramnagar_fort.jpg',
            'images/destination/varanasi/bharat_mata_temple.jpg'
        ],
        'festivals' => ['Dev Deepawali', 'Ganga Mahotsav', 'Maha Shivaratri', 'Holi Festival', 'Buddha Purnima', 'Diwali Festival', 'Chhath Puja'],
        'cuisines' => ['Kachori Sabzi', 'Tamatar Chaat', 'Baati Chokha', 'Malaiyo', 'Litti Chokha', 'Puri Sabzi', 'Banarasi Paan'],
        'famous_spots' => ['Blue Lassi Shop', 'Assi Ghat', 'Banaras Hindu University', 'Gyanvapi Mosque', 'Sankat Mochan Temple', 'Kashi Kalash Foundation', 'Man Mandir Ghat'],
        'nearby' => ['Sarnath', 'Allahabad', 'Ayodhya', 'Mirzapur', 'Chunar', 'Jaunpur', 'Vindhyachal'],
    ],
    [
        'name' => 'Kasol',
        'state' => 'Himachal Pradesh',
        'budget' => 'Budget',
        'type' => 'Offbeat',
        'duration' => 'Weekend',
        'image' => 'images/destination/kasol.jpg',
        'attractions' => ['Parvati Valley', 'Kheerganga Trek', 'Manikaran Sahib', 'Tosh Village', 'Chalal Trek', 'Rasol Village', 'Malana Village'],
        'attractions_images' => [
            'images/destination/kasol/parvati_valley.jpg',
            'images/destination/kasol/kheerganga_trek.jpg',
            'images/destination/kasol/manikaran_sahib.jpg',
            'images/destination/kasol/tosh_village.jpg',
            'images/destination/kasol/chalal_trek.jpg',
            'images/destination/kasol/rasol_village.jpg',
            'images/destination/kasol/malana_village.jpg'
        ],
        'festivals' => ['Indrasan Festival', 'Himalayan Music Festival', 'Parvati Peeth Festival', 'Holi Festival', 'Kullu Dussehra', 'Shivratri Festival', 'Baisakhi'],
        'cuisines' => ['Israeli Salad', 'Shakshuka', 'Tandoori Trout', 'Falafel', 'Hummus Platter', 'Nutella Pancakes', 'Himachali Dham'],
        'famous_spots' => ['Moon Dance Café', 'Jim Morrison Café', 'Tosh Village', 'Evergreen Café', 'Bhoj Café', 'Parvati River Bank', 'The Psychedelic'],
        'nearby' => ['Malana', 'Manikaran', 'Tosh', 'Pulga', 'Barshaini', 'Nakthan', 'Kutla'],
    ],
    [
        'name' => 'Rishikesh',
        'state' => 'Uttarakhand',
        'budget' => 'Budget',
        'type' => 'Spiritual',
        'duration' => '5-day',
        'image' => 'images/destination/rishikesh.jpg',
        'attractions' => ['Lakshman Jhula', 'Neelkanth Mahadev Temple', 'River Rafting', 'Triveni Ghat', 'The Beatles Ashram', 'Ram Jhula', 'Parmarth Niketan'],
        'attractions_images' => [
            'images/destination/rishikesh/lakshman_jhula.jpg',
            'images/destination/rishikesh/neelkanth_mahadev_temple.jpg',
            'images/destination/rishikesh/river_rafting.jpg',
            'images/destination/rishikesh/triveni_ghat.jpg',
            'images/destination/rishikesh/the_beatles_ashram.jpg',
            'images/destination/rishikesh/ram_jhula.jpg',
            'images/destination/rishikesh/parmarth_niketan.jpg'
        ],
        'festivals' => ['International Yoga Festival', 'Ganga Dussehra', 'Maha Shivaratri', 'Holi Festival', 'Diwali Festival', 'Kanwar Mela', 'Basant Panchami'],
        'cuisines' => ['Aloo Puri', 'Kachori', 'Chole Bhature', 'Lassi', 'Pahadi Thali', 'Samosa', 'Gulab Jamun'],
        'famous_spots' => ['The Beatles Ashram', 'Little Buddha Café', 'Ganga Beach', 'Café de Goa', 'Shivpuri Rafting Point', 'Trayambakeshwar Temple', 'Bairaj Lake'],
        'nearby' => ['Haridwar', 'Neelkanth Mahadev', 'Dehradun', 'Mussoorie', 'Shivpuri', 'Kanatal', 'Tehri'],
    ],
    [
        'name' => 'Tawang',
        'state' => 'Arunachal Pradesh',
        'budget' => 'Luxury',
        'type' => 'Offbeat',
        'duration' => 'Week-long',
        'image' => 'images/destination/tawang.jpg',
        'attractions' => ['Tawang Monastery', 'Sela Pass', 'Madhuri Lake', 'Nuranang Falls', 'Bum La Pass', 'Gorsam Chorten', 'Tawang War Memorial'],
        'attractions_images' => [
            'images/destination/tawang/tawang_monastery.jpg',
            'images/destination/tawang/sela_pass.jpg',
            'images/destination/tawang/madhuri_lake.jpg',
            'images/destination/tawang/nuranang_falls.jpg',
            'images/destination/tawang/bum_la_pass.jpg',
            'images/destination/tawang/gorsam_chorten.jpg',
            'images/destination/tawang/tawang_war_memorial.jpg'
        ],
        'festivals' => ['Torgya Festival', 'Losar Festival', 'Saka Dawa', 'Dukpa Tsheshi', 'Chokor Festival', 'Tawang Festival', 'Ganden Ngamchoe'],
        'cuisines' => ['Zan', 'Gyapa Khazi', 'Momos', 'Thukpa', 'Khura', 'Pika Pila', 'Lukter'],
        'famous_spots' => ['Tawang War Memorial', 'Craft Centre', 'Dragon Restaurant', 'PT Tso Lake', 'Sela Lake', 'Monpa Village', 'Tawang Market'],
        'nearby' => ['Bomdila', 'Zemithang', 'Dirang', 'Sangti Valley', 'Mandala Top', 'Thembang Village', 'Gorsam'],
    ],
    [
        'name' => 'Mcleodganj',
        'state' => 'Himachal Pradesh',
        'budget' => 'Budget',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/mcleodganj.jpg',
        'attractions' => ['Triund Trek', 'Dalai Lama Temple', 'Bhagsu Waterfall', 'Namgyal Monastery', 'St. John in the Wilderness', 'Naddi View Point', 'Kangra Fort'],
        'attractions_images' => [
            'images/destination/mcleodganj/triund_trek.jpg',
            'images/destination/mcleodganj/dalai_lama_temple.jpg',
            'images/destination/mcleodganj/bhagsu_waterfall.jpg',
            'images/destination/mcleodganj/namgyal_monastery.jpg',
            'images/destination/mcleodganj/st_john_in_the_wilderness.jpg',
            'images/destination/mcleodganj/naddi_view_point.jpg',
            'images/destination/mcleodganj/kangra_fort.jpg'
        ],
        'festivals' => ['Dal Festival', 'Losar Festival', 'Himalayan Festival', 'Holi Festival', 'Dharamshala Film Festival', 'Tibetan Uprising Day', 'Buddha Purnima'],
        'cuisines' => ['Tingmo', 'Thenthuk', 'Momos', 'Butter Tea', 'Shapale', 'Tsampa Porridge', 'Bhagsu Cake'],
        'famous_spots' => ['Illiterati Café', 'Norbulingka Institute', 'Tsuglagkhang Complex', 'Tibet Museum', 'Moonpeak Espresso', 'McLeod Ganj Market', 'Shiva Café'],
        'nearby' => ['Dharamkot', 'Bhagsu Nag', 'Kangra', 'Palampur', 'Kareri Lake', 'Billing', 'Masroor Temples'],
    ],
    [
        'name' => 'Chopta',
        'state' => 'Uttarakhand',
        'budget' => 'Budget',
        'type' => 'Offbeat',
        'duration' => '5-day',
        'image' => 'images/destination/chopta.jpg',
        'attractions' => ['Tungnath Temple', 'Deoria Tal', 'Chandrashila Trek', 'Kanchula Korak Musk Deer Sanctuary', 'Sari Village', 'Omkeshwar Temple', 'Ukhimath'],
        'attractions_images' => [
            'images/destination/chopta/tungnath_temple.jpg',
            'images/destination/chopta/deoria_tal.jpg',
            'images/destination/chopta/chandrashila_trek.jpg',
            'images/destination/chopta/kanchula_korak_musk_deer_sanctuary.jpg',
            'images/destination/chopta/sari_village.jpg',
            'images/destination/chopta/omkeshwar_temple.jpg',
            'images/destination/chopta/ukhimath.jpg'
        ],
        'festivals' => ['Makar Sankranti', 'Bikhauti Mela', 'Holi Festival', 'Diwali Festival', 'Nanda Devi Raj Jat', 'Butter Festival', 'Shivratri Festival'],
        'cuisines' => ['Chainsoo', 'Aloo Ke Gutke', 'Madua Roti', 'Kafuli', 'Phaanu', 'Jhangora Ki Kheer', 'Gahat Dal'],
        'famous_spots' => ['Local Campsites', 'Tungnath Café', 'Village Walks', 'Chopta Meadows', 'Anusuya Devi Temple', 'Kalimath Temple', 'Gopeshwar Market'],
        'nearby' => ['Rudraprayag', 'Ukhimath', 'Kedarnath', 'Guptkashi', 'Auli', 'Joshimath', 'Madmaheshwar'],
    ],
    [
        'name' => 'Meghamalai',
        'state' => 'Tamil Nadu',
        'budget' => 'Mid-range',
        'type' => 'Offbeat',
        'duration' => 'Weekend',
        'image' => 'images/destination/meghamalai.jpg',
        'attractions' => ['Highwavy Dam', 'Vellimalai', 'Suruli Falls', 'Meghamalai Wildlife Sanctuary', 'Manalar Falls', 'Maharaja Mettu', 'Thoovanam Falls'],
        'attractions_images' => [
            'images/destination/meghumalai/highwavy_dam.jpg',
            'images/destination/meghumalai/vellimalai.jpg',
            'images/destination/meghumalai/suruli_falls.jpg',
            'images/destination/meghumalai/meghamalai_wildlife_sanctuary.jpg',
            'images/destination/meghumalai/manalar_falls.jpg',
            'images/destination/meghumalai/maharaja_mettu.jpg',
            'images/destination/meghumalai/thoovanam_falls.jpg'
        ],
        'festivals' => ['Pongal', 'Chitra Pournami', 'Tamil New Year', 'Deepavali', 'Karthigai Deepam', 'Thaipusam', 'Aadi Perukku'],
        'cuisines' => ['Pongal', 'Chettinad Chicken', 'Meen Kuzhambu', 'Banana Bonda', 'Paruppu Vadai', 'Kambu Koozh', 'Pepper Rasam'],
        'famous_spots' => ['Tea Estates', 'Chellarkovil Viewpoint', 'Cloudlands Road', 'Meghamalai Viewpoint', 'Cardamom Plantations', 'Vattaparai Falls', 'Pothamedu'],
        'nearby' => ['Thekkady', 'Periyar Wildlife Sanctuary', 'Munnar', 'Kodaikanal', 'Madurai', 'Cumbum', 'Sabarimala'],
    ],
    [
        'name' => 'Spiti Valley',
        'state' => 'Himachal Pradesh',
        'budget' => 'Luxury',
        'type' => 'Offbeat',
        'duration' => 'Week-long',
        'image' => 'images/destination/spiti_valley.jpg',
        'attractions' => ['Key Monastery', 'Chandratal Lake', 'Pin Valley National Park', 'Tabo Monastery', 'Dhankar Monastery', 'Kibber Village', 'Langza Buddha Statue'],
        'attractions_images' => [
            'images/destination/spiti/key_monastery.jpg',
            'images/destination/spiti/chandratal_lake.jpg',
            'images/destination/spiti/pin_valley_national_park.jpg',
            'images/destination/spiti/tabo_monastery.jpg',
            'images/destination/spiti/dhankar_monastery.jpg',
            'images/destination/spiti/kibber_village.jpg',
            'images/destination/spiti/langza_buddha_statue.jpg'
        ],
        'festivals' => ['Gustor Festival', 'Tribal Fair', 'Ladarcha Fair', 'Tsuglagan Festival', 'Chakhar Festival', 'Fagli Festival', 'Losar Festival'],
        'cuisines' => ['Thukpa', 'Chhang', 'Momos', 'Butter Tea', 'Tsampa', 'Siddu', 'Paba'],
        'famous_spots' => ['Kaza Market', 'The Himalayan Café', 'Spiti River Walk', 'Hikkim Post Office', 'Komik Village', 'Dhankar Lake', 'Mud Village'],
        'nearby' => ['Tabo', 'Langza', 'Komic', 'Kaza', 'Hikkim', 'Dhankar', 'Nako'],
    ],
    [
        'name' => 'Ziro Valley',
        'state' => 'Arunachal Pradesh',
        'budget' => 'Mid-range',
        'type' => 'Offbeat',
        'duration' => '5-day',
        'image' => 'images/destination/ziro_valley.jpg',
        'attractions' => ['Talley Valley', 'Kile Pakho', 'Ziro Puto', 'Shivling at Siddeshwar Nath', 'Meghna Cave Temple', 'Pine Grove', 'Dolo Mando'],
        'attractions_images' => [
            'images/destination/ziro valley/talley_valley.jpg',
            'images/destination/ziro valley/kile_pakho.jpg',
            'images/destination/ziro valley/ziro_puto.jpg',
            'images/destination/ziro valley/shivling_at_siddeshwar_nath.jpg',
            'images/destination/ziro valley/meghna_cave_temple.jpg',
            'images/destination/ziro valley/pine_grove.jpg',
            'images/destination/ziro valley/dolo_mando.jpg'
        ],
        'festivals' => ['Ziro Music Festival', 'Dree Festival', 'Myoko Festival', 'Nyokum Festival', 'Siang River Festival', 'Boori Boot Festival', 'Solung Festival'],
        'cuisines' => ['Pika Pila', 'Bamboo Shoot Curry', 'Apong', 'Fish Stew', 'Lukter', 'Pe Hak', 'Dung Po'],
        'famous_spots' => ['Tarin Fish Farm', 'Ziro Pine Grove', 'Hapoli Market', 'Rice Fields', 'Hong Village', 'Ziro Church', 'Pine Bamboo Restaurant'],
        'nearby' => ['Itanagar', 'Daporijo', 'Along', 'Pasighat', 'Tuting', 'Majuli', 'Yingkiong'],
    ],
    [
        'name' => 'Auli',
        'state' => 'Uttarakhand',
        'budget' => 'Mid-range',
        'type' => 'Adventure',
        'duration' => '5-day',
        'image' => 'images/destination/auli.jpg',
        'attractions' => ['Skiing Slopes', 'Gurso Bugyal', 'Joshimath', 'Nanda Devi National Park', 'Auli Ropeway', 'Chattrakund Lake', 'Vishnuprayag'],
        'attractions_images' => [
            'images/destination/auli/skiing_slopes.jpg',
            'images/destination/auli/gurso_bugyal.jpg',
            'images/destination/auli/joshimath.jpg',
            'images/destination/auli/nanda_devi_national_park.jpg',
            'images/destination/auli/auli_ropeway.jpg',
            'images/destination/auli/chattrakund_lake.jpg',
            'images/destination/auli/vishnuprayag.jpg'
        ],
        'festivals' => ['Winter Carnival', 'Basant Panchami', 'Makar Sankranti', 'Nanda Devi Festival', 'Holi Festival', 'Diwali Festival', 'Shivratri Festival'],
        'cuisines' => ['Chainsoo', 'Gahat Dal', 'Aloo Ke Gutke', 'Bal Mithai', 'Kafuli', 'Jhangora Ki Kheer', 'Singori'],
        'famous_spots' => ['Ski Resorts', 'Auli Chair Lift', 'Joshimath Market', 'Narsingh Temple', 'Auli Lake', 'Chenab Lake', 'Kwani Bugyal'],
        'nearby' => ['Valley of Flowers', 'Badrinath', 'Hemkund Sahib', 'Mana Village', 'Tapkeshwar', 'Kedarnath', 'Chamoli'],
    ],
    [
        'name' => 'Gokarna',
        'state' => 'Karnataka',
        'budget' => 'Budget',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/gokarna.jpg',
        'attractions' => ['Om Beach', 'Kudle Beach', 'Mahabaleshwar Temple', 'Half Moon Beach', 'Gokarna', 'Gokarna Main Beach', 'Yana Caves'],
        'attractions_images' => [
            'images/destination/gokarna/om_beach.jpg',
            'images/destination/gokarna/kudle_beach.jpg',
            'images/destination/gokarna/mahabaleshwar_temple.jpg',
            'images/destination/gokarna/half_moon_beach.jpg',
            'images/destination/gokarna/gokarna.jpg',
            'images/destination/gokarna/gokarna_main_beach.jpg',
            'images/destination/gokarna/yana_caves.jpg'
        ],
        'festivals' => ['Shivaratri Festival', 'Gokarna Beach Festival', 'Holi Festival', 'Ganesh Chaturthi', 'Deepavali', 'Ugadi Festival', 'Vittala Purnima'],
        'cuisines' => ['Neer Dosa', 'Kane Rava Fry', 'Fish Curry', 'Banana Buns', 'Bangude Pulimunchi', 'Chicken Sukka', 'Mysore Pak'],
        'famous_spots' => ['Namaste Café', 'Half Moon Beach', 'Mirjan Fort', 'Prema Restaurant', 'Gokarna Cliffs', 'Sunset Point', 'Shri Hari Café'],
        'nearby' => ['Murudeshwar', 'Yana Caves', 'Karwar', 'Ankola', 'Dandeli', 'Udupi', 'Honnavar'],
    ],
    [
        'name' => 'Coorg',
        'state' => 'Karnataka',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/coorg.jpg',
        'attractions' => ['Abbey Falls', 'Mandalpatti', 'Dubare Elephant Camp', 'Talacauvery', 'Raja’s Seat', 'Iruppu Falls', 'Nagarhole National Park'],
        'attractions_images' => [
            'images/destination/coorg/abbey_falls.jpg',
            'images/destination/coorg/mandalpatti.jpg',
            'images/destination/coorg/dubare_elephant_camp.jpg',
            'images/destination/coorg/talacauvery.jpg',
            'images/destination/coorg/rajas_seat.jpg',
            'images/destination/coorg/iruppu_falls.jpg',
            'images/destination/coorg/nagarhole_national_park.jpg'
        ],
        'festivals' => ['Puthari Festival', 'Kailpodh Festival', 'Madikeri Dasara', 'Holi Festival', 'Deepavali', 'Tula Sankramana', 'Coorg Food Festival'],
        'cuisines' => ['Pandi Curry', 'Kadambuttu', 'Noolputtu', 'Coorgi Style Chicken Curry', 'Bamboo Shoot Curry', 'Akki Roti', 'Koli Curry'],
        'famous_spots' => ['Raja’s Seat', 'Namdroling Monastery', 'Coorg Cuisine', 'Madikeri Fort', 'Coffee Plantations', 'Tadiandamol Peak', 'Omkareshwara Temple'],
        'nearby' => ['Nagarhole', 'Madikeri', 'Mysore', 'Wayanad', 'Mangalore', 'Kushalnagar', 'Kabini'],
    ],
    [
        'name' => 'Andaman & Nicobar',
        'state' => 'Andaman & Nicobar',
        'budget' => 'Luxury',
        'type' => 'Adventure',
        'duration' => 'Week-long',
        'image' => 'images/destination/andaman_nicobar.jpg',
        'attractions' => ['Havelock Island', 'Radhanagar Beach', 'Cellular Jail', 'Neil Island', 'Ross Island', 'Barren Island', 'Elephant Beach'],
        'attractions_images' => [
            'images/destination/andaman n nico/havelock_island.jpg',
            'images/destination/andaman n nico/radhanagar_beach.jpg',
            'images/destination/andaman n nico/cellular_jail.jpg',
            'images/destination/andaman n nico/neil_island.jpg',
            'images/destination/andaman n nico/ross_island.jpg',
            'images/destination/andaman n nico/barren_island.jpg',
            'images/destination/andaman n nico/elephant_beach.jpg'
        ],
        'festivals' => ['Island Tourism Festival', 'Subhash Mela', 'Andaman Marathon', 'Monsoon Music Festival', 'Diwali Festival', 'Beach Festival', 'Film Festival'],
        'cuisines' => ['Fish Curry', 'Grilled Lobster', 'Prawn Masala', 'Coconut Prawn Curry', 'Chilli Crab', 'Tandoori Fish', 'Amritsari Kulcha'],
        'famous_spots' => ['SeaShell Bar & Lounge', 'Corbyn’s Cove', 'Aberdeen Bazaar', 'Viper Island', 'Samudrika Museum', 'Chatham Saw Mill', 'Marina Park'],
        'nearby' => ['Neil Island', 'Baratang Island', 'Diglipur', 'Little Andaman', 'Rangat', 'Long Island', 'Mayabunder'],
    ],
    [
        'name' => 'Darjeeling',
        'state' => 'West Bengal',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => '5-day',
        'image' => 'images/destination/darjeeling.jpg',
        'attractions' => ['Tiger Hill', 'Batasia Loop', 'Darjeeling Himalayan Railway', 'Padmaja Naidu Himalayan Zoo', 'Peace Pagoda', 'Ghoom Monastery', 'Rock Garden'],
        'attractions_images' => [
            'images/destination/darjeeling/tiger_hill.jpg',
            'images/destination/darjeeling/batasia_loop.jpg',
            'images/destination/darjeeling/darjeeling_himalayan_railway.jpg',
            'images/destination/darjeeling/padmaja_naidu_himalayan_zoo.jpg',
            'images/destination/darjeeling/peace_pagoda.jpg',
            'images/destination/darjeeling/ghoom_monastery.jpg',
            'images/destination/darjeeling/rock_garden.jpg'
        ],
        'festivals' => ['Darjeeling Carnival', 'Losar Festival', 'Teej Festival', 'Durga Puja', 'Holi Festival', 'Orange Festival', 'Tea Festival'],
        'cuisines' => ['Thukpa', 'Momos', 'Sel Roti', 'Churpee Soup', 'Aloo Dum', 'Gundruk', 'Sael Roti'],
        'famous_spots' => ['Glenary’s Bakery', 'Chowrasta', 'Japanese Peace Pagoda', 'Tea Gardens', 'Mall Road', 'Keventer’s Café', 'Himalayan Mountaineering Institute'],
        'nearby' => ['Kalimpong', 'Mirik', 'Kurseong', 'Gangtok', 'Pelling', 'Lava', 'Sikkim'],
    ],
    [
        'name' => 'Lonavala & Khandala',
        'state' => 'Maharashtra',
        'budget' => 'Budget',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/lonavala_khandala.jpg',
        'attractions' => ['Tiger’s Leap', 'Bhushi Dam', 'Rajmachi Fort', 'Karla Caves', 'Lohagad Fort', 'Pawna Lake', 'Duke’s Nose'],
        'attractions_images' => [
            'images/destination/lonavala/tigers_leap.jpg',
            'images/destination/lonavala/bhushi_dam.jpg',
            'images/destination/lonavala/rajmachi_fort.jpg',
            'images/destination/lonavala/karla_caves.jpg',
            'images/destination/lonavala/lohagad_fort.jpg',
            'images/destination/lonavala/pawna_lake.jpg',
            'images/destination/lonavala/dukes_nose.jpg'
        ],
        'festivals' => ['Ganesh Chaturthi', 'Diwali Trekking Events', 'Monsoon Festival', 'Holi Festival', 'Shivratri Festival', 'Khandala Food Festival', 'Pawna Camping Festival'],
        'cuisines' => ['Vada Pav', 'Misal Pav', 'Chikki', 'Puran Poli', 'Pav Bhaji', 'Sabudana Vada', 'Bhel Puri'],
        'famous_spots' => ['Cooper’s Chikki', 'Lion’s Point', 'German Bakery', 'Kune Falls', 'Sunset Point', 'Della Adventure Park', 'Wax Museum'],
        'nearby' => ['Karla Caves', 'Pawna Lake', 'Maval', 'Kamshet', 'Talegaon', 'Khopoli', 'Igatpuri'],
    ],
    [
        'name' => 'Mahabaleshwar',
        'state' => 'Maharashtra',
        'budget' => 'Mid-range',
        'type' => 'Chill',
        'duration' => 'Weekend',
        'image' => 'images/destination/mahabaleshwar.jpg',
        'attractions' => ['Elephant’s Head Point', 'Venna Lake', 'Pratapgad Fort', 'Mapro Garden', 'Lingmala Falls', 'Wilson Point', 'Kate’s Point'],
        'attractions_images' => [
            'images/destination/mahabaleshwar/elephants_head_point.jpg',
            'images/destination/mahabaleshwar/venna_lake.jpg',
            'images/destination/mahabaleshwar/pratapgad_fort.jpg',
            'images/destination/mahabaleshwar/mapro_garden.jpg',
            'images/destination/mahabaleshwar/lingmala_falls.jpg',
            'images/destination/mahabaleshwar/wilson_point.jpg',
            'images/destination/mahabaleshwar/kates_point.jpg'
        ],
        'festivals' => ['Strawberry Festival', 'Holi Celebration', 'Ganesh Chaturthi', 'Diwali Festival', 'Monsoon Festival', 'Shivratri Festival', 'Mahabaleshwar Fair'],
        'cuisines' => ['Strawberries with Cream', 'Puran Poli', 'Bhakri', 'Kanda Bhaji', 'Misal Pav', 'Corn Patties', 'Pav Bhaji'],
        'famous_spots' => ['Mapro Garden', 'Lingmala Falls', 'Venna Lake Boating', 'Arthur’s Seat', 'Sunset Point', 'Strawberry Farms', 'Mahabaleshwar Temple'],
        'nearby' => ['Panchgani', 'Tapola', 'Wai', 'Satara', 'Raigad', 'Pratapgad', 'Kaas Plateau'],
    ],
    [
        'name' => 'Tirthan Valley',
        'state' => 'Himachal Pradesh',
        'budget' => 'Budget',
        'type' => 'Offbeat',
        'duration' => '5-day',
        'image' => 'images/destination/tirthan_valley.jpg',
        'attractions' => ['Great Himalayan National Park', 'Serolsar Lake', 'Jalori Pass', 'Chhoie Waterfall', 'Tirthan River', 'Lambri Village', 'Raghupur Fort'],
        'attractions_images' => [
            'images/destination/tirthan valleyu/great_himalayan_national_park.jpg',
            'images/destination/tirthan valleyu/serolsar_lake.jpg',
            'images/destination/tirthan valleyu/jalori_pass.jpg',
            'images/destination/tirthan valleyu/chhoie_waterfall.jpg',
            'images/destination/tirthan valleyu/tirthan_river.jpg',
            'images/destination/tirthan valleyu/lambri_village.jpg',
            'images/destination/tirthan valleyu/raghupur_fort.jpg'
        ],
        'festivals' => ['Fagli Festival', 'Holi Festival', 'Kullu Dussehra', 'Losar Festival', 'Sazo Festival', 'Baisakhi Festival', 'Tirthan Fish Festival'],
        'cuisines' => ['Siddu', 'Chana Madra', 'Bhatura', 'Rajma Chawal', 'Lingdi Aloo', 'Kullu Trout', 'Babru'],
        'famous_spots' => ['Raju’s Cottage', 'Gushaini Trails', 'River Crossing Camps', 'Trout Fishing Spots', 'Banjar Market', 'Sai Ropa', 'Sojha Village'],
        'nearby' => ['Shoja', 'Jibhi', 'Manali', 'Kullu', 'Aut', 'Banjar', 'Mandi'],
    ],
    [
        'name' => 'Puducherry',
        'state' => 'Puducherry',
        'budget' => 'Mid-range',
        'type' => 'Party',
        'duration' => 'Weekend',
        'image' => 'images/destination/puducherry.jpg',
        'attractions' => ['Promenade Beach', 'Auroville', 'Paradise Beach', 'Sri Aurobindo Ashram', 'French Quarter', 'Puducherry Museum', 'Botanical Garden'],
        'attractions_images' => [
            'images/destination/puducherry/promenade_beach.jpg',
            'images/destination/puducherry/auroville.jpg',
            'images/destination/puducherry/paradise_beach.jpg',
            'images/destination/puducherry/sri_aurobindo_ashram.jpg',
            'images/destination/puducherry/french_quarter.jpg',
            'images/destination/puducherry/puducherry_museum.jpg',
            'images/destination/puducherry/botanical_garden.jpg'
        ],
        'festivals' => ['Bastille Day', 'Pondicherry Heritage Festival', 'Pongal Festival', 'Deepavali', 'French Food Festival', 'Yoga Festival', 'Masi Magam'],
        'cuisines' => ['Creole Curries', 'Baguettes', 'Seafood Vindaloo', 'Stuffed Crab', 'Prawn Balchao', 'Mutton Korma', 'Pain au Chocolat'],
        'famous_spots' => ['Café Des Arts', 'White Town', 'Rock Beach', 'Le Café', 'Serenity Beach', 'Goubert Market', 'La Maison Rose'],
        'nearby' => ['Auroville', 'Paradise Beach', 'Chidambaram', 'Mahabalipuram', 'Kanchipuram', 'Pichavaram Mangroves', 'Tharangambadi'],
    ],
];

return $destinations;

